# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    "aro-0.0.0-JSD1QmbSNgDrBkBPRoDPwy1rN1ABGBa7B1NzC-lqnGxw" = fetchZigGit {
      name = "aro";
      url = "https://codeberg.org/ifreund/arocc";
      rev = "1bf978f1e63d4fe66a90b6637ba709e9abc3c854";
      hash = "sha256-UjLpDXeD5supXFUpa4+q9Uc9aTVglZrIp6pM1qyv1+A=";
    };
    "pixman-0.3.0-LClMnz2VAAAs7QSCGwLimV5VUYx0JFnX5xWU6HwtMuDX" = fetchzip {
      name = "pixman";
      url = "https://codeberg.org/ifreund/zig-pixman/archive/v0.3.0.tar.gz";
      hash = "sha256-8tA4auo5FEI4IPnomV6bkpQHUe302tQtorFQZ1l14NU=";
    };
    "translate_c-0.0.0-Q_BUWlL1BgD7PmL27vTsccyNCOvKb-B65O5Ki1ZKm-ED" = fetchZigGit {
      name = "translate_c";
      url = "https://codeberg.org/ifreund/translate-c";
      rev = "64570104eeed461dc221e77574cd3f1c5b7eb974";
      hash = "sha256-ZQnT0XeVxcs5Px1Y8pNvqUOXzj0UnVC+Ijnr5ePvF/M=";
    };
    "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX" = fetchzip {
      name = "wayland";
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
    };
    "wlroots-0.20.2-dev-jmOlcrJuBABMWPGDKK86BO7zrfmxm17nimqFb0gffZTn" = fetchZigGit {
      name = "wlroots";
      url = "https://codeberg.org/ifreund/zig-wlroots";
      rev = "c183af18ae35dd5fb3dde709697c8f84bb1dc7f3";
      hash = "sha256-bGPrJFZBMq3aa3Ar9MEl4ta5o/QNyDfiPrBk2fW0BmU=";
    };
    "xkbcommon-0.3.0-VDqIe3K9AQB2fG5ZeRcMC9i7kfrp5m2rWgLrmdNn9azr" = fetchzip {
      name = "xkbcommon";
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.3.0.tar.gz";
      hash = "sha256-e5bPEfxl4SQf0cqccLt/py1KOW1+Q1+kWZUEXBbh9oQ=";
    };
    "xkbcommon-0.4.0-VDqIe0i2AgDRsok2GpMFYJ8SVhQS10_PI2M_CnHXsJJZ" = fetchzip {
      name = "xkbcommon";
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.4.0.tar.gz";
      hash = "sha256-zQkmP/cuhAtjOLqYS5D15khKzpqyhbyZ0TD6/8jOkqE=";
    };
  };

  # The packages whose own manifest declares a dependency by `.path`. Zig
  # 0.16.0 cannot build these through `zig build --system`: it spins in
  # userspace forever, because a `.path` dependency's hash is computed against
  # the system package directory during the fetch and against the real global
  # cache afterwards, and in that mode the two disagree. A package that wants
  # `--system` copies each of these into its build root and passes `--fork=`;
  # see the README.
  pathDependencyPackages = [
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what
# `zig build --system` wants.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_16 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Each package gets a directory of its own to work in, since `zig fetch`
    # leaves what it unpacked in `zig-pkg/` under the directory it ran in.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work/src" "$work/cache/tmp"
      # workaround https://codeberg.org/ziglang/zig/issues/31866
      # https://github.com/Cloudef/zig2nix/issues/54
      touch "$work/src/build.zig"
      # `zig fetch` recompresses every package into `p/` at gzip level 9 for
      # its own cache, which is nearly all of its time and of no use here.
      # With `p` a file rather than a directory that step fails at once --
      # Zig warns, and carries on -- and the package is left in `zig-pkg/`.
      touch "$work/cache/p"

      local hash
      if ! hash="$(cd "$work/src" && zig fetch --global-cache-dir "$work/cache" "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      mv "$work/src/zig-pkg/$1" "$out/$1"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    # `-r` because otherwise xargs runs `unpack` once, with no arguments, when
    # there are no packages at all, and the build fails.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -r -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
