/* Generated by wayland-scanner 1.24.0 */

#ifndef RIVER_STATUS_UNSTABLE_V1_SERVER_PROTOCOL_H
#define RIVER_STATUS_UNSTABLE_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server-core.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_river_status_unstable_v1 The river_status_unstable_v1 protocol
 * @section page_ifaces_river_status_unstable_v1 Interfaces
 * - @subpage page_iface_zriver_status_manager_v1 - manage river status objects
 * - @subpage page_iface_zriver_output_status_v1 - track output tags and focus
 * - @subpage page_iface_zriver_seat_status_v1 - track seat focus
 * @section page_copyright_river_status_unstable_v1 Copyright
 * <pre>
 *
 * Copyright 2020 The River Developers
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 * </pre>
 */
struct wl_output;
struct wl_seat;
struct zriver_output_status_v1;
struct zriver_seat_status_v1;
struct zriver_status_manager_v1;

#ifndef ZRIVER_STATUS_MANAGER_V1_INTERFACE
#define ZRIVER_STATUS_MANAGER_V1_INTERFACE
/**
 * @page page_iface_zriver_status_manager_v1 zriver_status_manager_v1
 * @section page_iface_zriver_status_manager_v1_desc Description
 *
 * A global factory for objects that receive status information specific
 * to river. It could be used to implement, for example, a status bar.
 * @section page_iface_zriver_status_manager_v1_api API
 * See @ref iface_zriver_status_manager_v1.
 */
/**
 * @defgroup iface_zriver_status_manager_v1 The zriver_status_manager_v1 interface
 *
 * A global factory for objects that receive status information specific
 * to river. It could be used to implement, for example, a status bar.
 */
extern const struct wl_interface zriver_status_manager_v1_interface;
#endif
#ifndef ZRIVER_OUTPUT_STATUS_V1_INTERFACE
#define ZRIVER_OUTPUT_STATUS_V1_INTERFACE
/**
 * @page page_iface_zriver_output_status_v1 zriver_output_status_v1
 * @section page_iface_zriver_output_status_v1_desc Description
 *
 * This interface allows clients to receive information about the current
 * windowing state of an output.
 * @section page_iface_zriver_output_status_v1_api API
 * See @ref iface_zriver_output_status_v1.
 */
/**
 * @defgroup iface_zriver_output_status_v1 The zriver_output_status_v1 interface
 *
 * This interface allows clients to receive information about the current
 * windowing state of an output.
 */
extern const struct wl_interface zriver_output_status_v1_interface;
#endif
#ifndef ZRIVER_SEAT_STATUS_V1_INTERFACE
#define ZRIVER_SEAT_STATUS_V1_INTERFACE
/**
 * @page page_iface_zriver_seat_status_v1 zriver_seat_status_v1
 * @section page_iface_zriver_seat_status_v1_desc Description
 *
 * This interface allows clients to receive information about the current
 * focus of a seat. Note that (un)focused_output events will only be sent
 * if the client has bound the relevant wl_output globals.
 * @section page_iface_zriver_seat_status_v1_api API
 * See @ref iface_zriver_seat_status_v1.
 */
/**
 * @defgroup iface_zriver_seat_status_v1 The zriver_seat_status_v1 interface
 *
 * This interface allows clients to receive information about the current
 * focus of a seat. Note that (un)focused_output events will only be sent
 * if the client has bound the relevant wl_output globals.
 */
extern const struct wl_interface zriver_seat_status_v1_interface;
#endif

/**
 * @ingroup iface_zriver_status_manager_v1
 * @struct zriver_status_manager_v1_interface
 */
struct zriver_status_manager_v1_interface {
	/**
	 * destroy the river_status_manager object
	 *
	 * This request indicates that the client will not use the
	 * river_status_manager object any more. Objects that have been
	 * created through this instance are not affected.
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * create an output status object
	 *
	 * This creates a new river_output_status object for the given
	 * wl_output.
	 */
	void (*get_river_output_status)(struct wl_client *client,
					struct wl_resource *resource,
					uint32_t id,
					struct wl_resource *output);
	/**
	 * create a seat status object
	 *
	 * This creates a new river_seat_status object for the given
	 * wl_seat.
	 */
	void (*get_river_seat_status)(struct wl_client *client,
				      struct wl_resource *resource,
				      uint32_t id,
				      struct wl_resource *seat);
};


/**
 * @ingroup iface_zriver_status_manager_v1
 */
#define ZRIVER_STATUS_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_status_manager_v1
 */
#define ZRIVER_STATUS_MANAGER_V1_GET_RIVER_OUTPUT_STATUS_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_status_manager_v1
 */
#define ZRIVER_STATUS_MANAGER_V1_GET_RIVER_SEAT_STATUS_SINCE_VERSION 1

/**
 * @ingroup iface_zriver_output_status_v1
 * @struct zriver_output_status_v1_interface
 */
struct zriver_output_status_v1_interface {
	/**
	 * destroy the river_output_status object
	 *
	 * This request indicates that the client will not use the
	 * river_output_status object any more.
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};

#define ZRIVER_OUTPUT_STATUS_V1_FOCUSED_TAGS 0
#define ZRIVER_OUTPUT_STATUS_V1_VIEW_TAGS 1
#define ZRIVER_OUTPUT_STATUS_V1_URGENT_TAGS 2
#define ZRIVER_OUTPUT_STATUS_V1_LAYOUT_NAME 3
#define ZRIVER_OUTPUT_STATUS_V1_LAYOUT_NAME_CLEAR 4

/**
 * @ingroup iface_zriver_output_status_v1
 */
#define ZRIVER_OUTPUT_STATUS_V1_FOCUSED_TAGS_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_output_status_v1
 */
#define ZRIVER_OUTPUT_STATUS_V1_VIEW_TAGS_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_output_status_v1
 */
#define ZRIVER_OUTPUT_STATUS_V1_URGENT_TAGS_SINCE_VERSION 2
/**
 * @ingroup iface_zriver_output_status_v1
 */
#define ZRIVER_OUTPUT_STATUS_V1_LAYOUT_NAME_SINCE_VERSION 4
/**
 * @ingroup iface_zriver_output_status_v1
 */
#define ZRIVER_OUTPUT_STATUS_V1_LAYOUT_NAME_CLEAR_SINCE_VERSION 4

/**
 * @ingroup iface_zriver_output_status_v1
 */
#define ZRIVER_OUTPUT_STATUS_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_zriver_output_status_v1
 * Sends an focused_tags event to the client owning the resource.
 * @param resource_ The client's resource
 * @param tags 32-bit bitfield
 */
static inline void
zriver_output_status_v1_send_focused_tags(struct wl_resource *resource_, uint32_t tags)
{
	wl_resource_post_event(resource_, ZRIVER_OUTPUT_STATUS_V1_FOCUSED_TAGS, tags);
}

/**
 * @ingroup iface_zriver_output_status_v1
 * Sends an view_tags event to the client owning the resource.
 * @param resource_ The client's resource
 * @param tags array of 32-bit bitfields
 */
static inline void
zriver_output_status_v1_send_view_tags(struct wl_resource *resource_, struct wl_array *tags)
{
	wl_resource_post_event(resource_, ZRIVER_OUTPUT_STATUS_V1_VIEW_TAGS, tags);
}

/**
 * @ingroup iface_zriver_output_status_v1
 * Sends an urgent_tags event to the client owning the resource.
 * @param resource_ The client's resource
 * @param tags 32-bit bitfield
 */
static inline void
zriver_output_status_v1_send_urgent_tags(struct wl_resource *resource_, uint32_t tags)
{
	wl_resource_post_event(resource_, ZRIVER_OUTPUT_STATUS_V1_URGENT_TAGS, tags);
}

/**
 * @ingroup iface_zriver_output_status_v1
 * Sends an layout_name event to the client owning the resource.
 * @param resource_ The client's resource
 * @param name layout name
 */
static inline void
zriver_output_status_v1_send_layout_name(struct wl_resource *resource_, const char *name)
{
	wl_resource_post_event(resource_, ZRIVER_OUTPUT_STATUS_V1_LAYOUT_NAME, name);
}

/**
 * @ingroup iface_zriver_output_status_v1
 * Sends an layout_name_clear event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zriver_output_status_v1_send_layout_name_clear(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ZRIVER_OUTPUT_STATUS_V1_LAYOUT_NAME_CLEAR);
}

/**
 * @ingroup iface_zriver_seat_status_v1
 * @struct zriver_seat_status_v1_interface
 */
struct zriver_seat_status_v1_interface {
	/**
	 * destroy the river_seat_status object
	 *
	 * This request indicates that the client will not use the
	 * river_seat_status object any more.
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};

#define ZRIVER_SEAT_STATUS_V1_FOCUSED_OUTPUT 0
#define ZRIVER_SEAT_STATUS_V1_UNFOCUSED_OUTPUT 1
#define ZRIVER_SEAT_STATUS_V1_FOCUSED_VIEW 2
#define ZRIVER_SEAT_STATUS_V1_MODE 3

/**
 * @ingroup iface_zriver_seat_status_v1
 */
#define ZRIVER_SEAT_STATUS_V1_FOCUSED_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_seat_status_v1
 */
#define ZRIVER_SEAT_STATUS_V1_UNFOCUSED_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_seat_status_v1
 */
#define ZRIVER_SEAT_STATUS_V1_FOCUSED_VIEW_SINCE_VERSION 1
/**
 * @ingroup iface_zriver_seat_status_v1
 */
#define ZRIVER_SEAT_STATUS_V1_MODE_SINCE_VERSION 3

/**
 * @ingroup iface_zriver_seat_status_v1
 */
#define ZRIVER_SEAT_STATUS_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_zriver_seat_status_v1
 * Sends an focused_output event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zriver_seat_status_v1_send_focused_output(struct wl_resource *resource_, struct wl_resource *output)
{
	wl_resource_post_event(resource_, ZRIVER_SEAT_STATUS_V1_FOCUSED_OUTPUT, output);
}

/**
 * @ingroup iface_zriver_seat_status_v1
 * Sends an unfocused_output event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zriver_seat_status_v1_send_unfocused_output(struct wl_resource *resource_, struct wl_resource *output)
{
	wl_resource_post_event(resource_, ZRIVER_SEAT_STATUS_V1_UNFOCUSED_OUTPUT, output);
}

/**
 * @ingroup iface_zriver_seat_status_v1
 * Sends an focused_view event to the client owning the resource.
 * @param resource_ The client's resource
 * @param title title of the focused view
 */
static inline void
zriver_seat_status_v1_send_focused_view(struct wl_resource *resource_, const char *title)
{
	wl_resource_post_event(resource_, ZRIVER_SEAT_STATUS_V1_FOCUSED_VIEW, title);
}

/**
 * @ingroup iface_zriver_seat_status_v1
 * Sends an mode event to the client owning the resource.
 * @param resource_ The client's resource
 * @param name name of the mode
 */
static inline void
zriver_seat_status_v1_send_mode(struct wl_resource *resource_, const char *name)
{
	wl_resource_post_event(resource_, ZRIVER_SEAT_STATUS_V1_MODE, name);
}

#ifdef  __cplusplus
}
#endif

#endif
