---
verbatim:
  cabal-version:    3.4

name:               hswm
version:            0.1.0.0
synopsis:           Wayland window manager for River
description:        Wayland window manager for River
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
# copyright:
build-type:         Simple
extra-doc-files:    README.md
#                  CHANGELOG.md
extra-source-files:
  - Makefile
  - cbits/*.c

library:
  source-dirs: src
  exposed-modules:
    # Note: c2hs is clunky about the order of exposed modules :(
    - Wayland.FFI
    - Wayland
    - River.XKB.Config.FFI
    - River.XKB.Config
    - River.XKB.Bindings.FFI
    - River.XKB.Bindings.MiscFFI
    - River.XKB.Bindings
    - River.WMP.FFI
    - River.WMP.MiscFFI
    - River.WMP
    - River
    - HSWM.XKB.FFI
    - HSWM.XKB
    - HSWM.Util.Posix
    - HSWM.Utils
    - HSWM.Types
    - HSWM.StackSet
    - HSWM.BufferPool
    - HSWM.Seats
    - HSWM.Windows
    - HSWM.Outputs
    - HSWM.Operations
    - HSWM.Main
    - HSWM.Util.Waybar
    - HSWM.Layout
    - HSWM.Core
    - HSWM.Wallpaper
    - HSWM.Config
    - HSWM
    - Core
  other-modules: Prelude
  generated-other-modules: Paths_hswm
  dependencies:
    - &base base >=4.20.2.0
    - containers
    - data-default
    - derive-storable
    - logging
    - mtl
    - pretty-simple
    - stm
    - text
    - transformers
    - typerep-map
    - unix
    - hswm-bindings # Generated C bindings
    - directory
    - vector
    - JuicyPixels
  pkgconfig-depends:
    - wayland-protocols
    - wayland-client
    - xkbcommon
    - pixman-1
    - gtk+-3.0 # XXX not strictly needed /here/
  extra-libraries:
    - wayland-client
    - xkbcommon
    - pixman-1
  include-dirs:
    - cbits
  c-sources:
    - cbits/*-protocol.c
  build-tools:
    # Note: may need to "cabal update for this to start working
    - c2hs:c2hs
    #- hs-bindgen:hs-bindgen-cli
  ghc-options: &common-ghc-options
    -Wall -Wunused-packages
  language: &default-language
    GHC2024
  default-extensions: &default-extensions
    - RecordWildCards
    - OverloadedRecordDot
    - DuplicateRecordFields
    - OverloadedStrings
    - DeriveAnyClass

executables:
  hswm:
    main: Main.hs
    source-dirs: app
    dependencies:
      - *base
      - hswm
      - hswm-bindings
    pkgconfig-depends: wayland-client
    extra-libraries: wayland-client
    ghc-options: *common-ghc-options
    language: *default-language
    default-extensions: *default-extensions
