---
verbatim:
  cabal-version:    3.4

name:               hswm
version: &version   0.1.0.0
synopsis:           Wayland window manager for River
description:        Wayland window manager for River
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
# copyright:
build-type:         Simple
extra-doc-files:    README.md
#                  CHANGELOG.md
extra-source-files:
  - Makefile
  - hswm-bindings/include/*.h
  - hswm-bindings/cbits/*.c

_common/language: &language
  language: GHC2024
  default-extensions: &default-extensions
    - RecordWildCards
    - OverloadedRecordDot
    - DuplicateRecordFields
    - OverloadedStrings
    - DerivingVia
    - DeriveAnyClass
    - PackageImports
  ghc-options: &common-ghc-options
    -Wall -Wunused-packages

internal-libraries:
  hswm-prelude:
    <<: *language
    source-dirs: hswm-prelude
    exposed-modules:
      - HSWM.Prelude
    other-modules: []
    dependencies:
      - name: base
        version: &base-version '>=4.20.2.0'
      - text
      - mtl
      - logging
      - data-default
      - stm

library:
  <<: *language
  source-dirs: src
  exposed-modules:
    # Note: c2hs is clunky about the order of exposed modules :(
    - Wayland.FFI
    - Wayland
    - River.XKB.Config.FFI
    - River.XKB.Config
    - River.XKB.Bindings.FFI
    - River.XKB.Bindings.MiscFFI
    - River.XKB.Bindings
    - River.WMP.FFI
    - River.WMP.MiscFFI
    - River.WMP
    - River
    - HSWM.Actions.WindowNavigation
    - HSWM.BufferPool
    - HSWM.Config
    - HSWM.Core
    - HSWM.Layout
    - HSWM.Main
    - HSWM.Operations
    - HSWM.Outputs
    - HSWM.Seats
    - HSWM.StackSet
    - HSWM.Util.Posix
    - HSWM.Util.Types
    - HSWM.Util.Waybar
    - HSWM.Utils
    - HSWM.Wallpaper
    - HSWM.Windows
    - HSWM.XKB
    - HSWM.XKB.FFI
    - HSWM.Util.IPC
    - HSWM
    - Core # TODO: refactor/rename
  other-modules: []
  generated-other-modules:
    - Paths_hswm
  dependencies:
    - &hswm-prelude
      name: hswm:hswm-prelude
      mixin:
        - (HSWM.Prelude as Prelude)
    - &base-noprelude
      name: base
      version: *base-version
      mixin:
        - hiding (Prelude)
    - containers
    - data-default
    - derive-storable
    #- logging
    #- mtl
    - pretty-simple
    #- stm
    #- text
    - transformers
    - typerep-map
    - unix
    - hswm-bindings # Generated C bindings
    - directory
    - vector
    - JuicyPixels
    - network
    - bytestring
    - aeson
    - c-expr-runtime # XXX: needded to avoid linker problems?
    - hs-bindgen-runtime # XXX: needded to avoid linker problems?
  pkgconfig-depends:
    - xkbcommon
    #- wayland-protocols
    #- wayland-client
    #- pixman-1
    #- gtk+-3.0 # XXX not strictly needed /here/
  extra-libraries: []
    #- wayland-client
    #- xkbcommon
    #- pixman-1
    #- gtk-3 # XXX not strictly needed /here/
  include-dirs:
    - hswm-bindings/include
  c-sources:
    - hswm-bindings/cbits/*-protocol.c
  build-tools:
    - c2hs:c2hs  # Note: may need to "cabal update for this to start working

executables:
  hswm:
    <<: *language
    main: Main.hs
    source-dirs: app
    dependencies:
      - base
      - hswm
      - hswm-bindings
      - containers
    ghc-options:
      - *common-ghc-options
      - -threaded

  hswmctl:
    <<: *language
    main: Main.hs
    source-dirs: app-ctl
    dependencies:
      - base
      - hswm
    ghc-options:
      - *common-ghc-options
      - -threaded
