-- vim: ft=cabalproject

-- Cabal, cabal-install 3.17 (unreleased)
source-repository-package
  type: git
  location: https://github.com/haskell/cabal
  -- branch: master
  tag: bc27d17d93851f78070be6f8ee0724f58168ee97
  -- tag: 832789ea85297f0b5c3f92d63f8238eb3241614d
  subdir:
    Cabal
    Cabal-hooks
    Cabal-syntax
    cabal-install
    cabal-install-solver
    hooks-exe
  --sha256: 16sx9nl272ax7n292v7jqxwqzn5k2ipak99xd32q13702558rsp1

-- old 0x3rwmldnzzyi718h48ggm0630wiz2bbjgp2f3wpcvyqb46gxwcw

-- cabal-doctest fixed for Cabal-3.17
source-repository-package
  type: git
  location: https://github.com/SimSaladin/cabal-doctest
  branch: cabal-3.17
  tag: 615d46e72a47062cd76abe4bdb43d088cc3e0bdb
  --sha256: 1vn4w9k5mc1mzlhpxaai1j70svvdvfkl7npl7rnabp35vczpp39k
