-- vim: ft=cabalproject

-- hs-bindgen (unreleased) (28-05-2026)
source-repository-package
  type: git
  location: https://github.com/well-typed/hs-bindgen
  branch: main
  tag: 24ed914383635226710306cd12499f09d61adb40
  subdir:
    c-expr-runtime
    c-expr-dsl
    hs-bindgen
    hs-bindgen-runtime
  --sha256: sha256-kYyOI/Er47TMHSyNI+qMHaaPHN1lD9a2epAcKLPvPwQ=

-- libclang-bindings (unreleased) for hs-bindgen (22-05-2026)
source-repository-package
  type: git
  location: https://github.com/well-typed/libclang-bindings
  tag: 51b4b4972ea7ee8f7848f962e8524b6cd3eb4a84
  subdir: libclang-bindings
  --sha256: 0ah4fjl3mfacz1dgpcwmjlm5ay2c4khv5c54s28b6b5fhvv9zy3v

-- doxygen-parser (unreleased) for hs-bindgen (04-05-2026)
source-repository-package
  type: git
  location: https://github.com/well-typed/doxygen-parser
  tag: 33b5074eb5122062ac41fa8b9ed0596d39913b63
  --sha256: 0xj6lilgj70rs3fcc86gl30z5imghx9jgiwalvw9q8ldlpd7hvgc
