-- vim: ft=cabalproject

-- hs-bindgen (unreleased) @ Jul 10, 2026
source-repository-package
  type: git
  location: https://github.com/well-typed/hs-bindgen
  -- branch: main
  tag: 73657aba23579cd7a854d4d5458ea002d27175a4
  subdir: hs-bindgen hs-bindgen-runtime
  --sha256: sha256-8pjasTPbgS6ki7mnm8WDZY/+z+hCFl5SGl6O/CCH3hc=

-- c-expr (unreleased)
source-repository-package
  type: git
  location: https://github.com/well-typed/c-expr
  tag: e7dcc55a3799b4bac10a15fb764d6bbba546b787
  subdir: c-expr-runtime c-expr-dsl
  --sha256: 1n1aa83gj0h8ikdym3jsgq3ah49bksgmzdyh5snp8kj3c6wxwzx0

-- libclang-bindings (unreleased) for hs-bindgen
source-repository-package
  type: git
  location: https://github.com/well-typed/libclang-bindings
  tag: ef67437045c45a32d7d1aa7166043937c1259d7f
  subdir: libclang-bindings
  --sha256: 009nfyxw8i97aik9w66v7h84w05yxp644jfq8lmmradp1vgac4n8

-- doxygen-parser (unreleased) for hs-bindgen (04-05-2026)
source-repository-package
  type: git
  location: https://github.com/well-typed/doxygen-parser
  tag: 33b5074eb5122062ac41fa8b9ed0596d39913b63
  --sha256: 0xj6lilgj70rs3fcc86gl30z5imghx9jgiwalvw9q8ldlpd7hvgc
