-- vim: ft=cabalproject

source-repository-package
   type: git
   location: https://github.com/well-typed/hs-bindgen
   tag:      855a3777b85f9238674bdc778ed1a050bcbb5967
   subdir:   hs-bindgen hs-bindgen-runtime
   --sha256: 135ac451pkr7phmyvjarxg0vzpqzhyis8l9ffq2v87h59fv8f579

source-repository-package
   type:     git
   location: https://github.com/well-typed/libclang-bindings
   tag:      d67fb98d54301f1ef1bce08c643808d704fec813
   subdir:   libclang-bindings
   --sha256: 0x8fkaxdcnq4b5fhblsnm41bh1rhhjvypp6z6ws1a4wisal2bpar

source-repository-package
   type:     git
   location: https://github.com/well-typed/c-expr
   tag:      6a18018ac1b91c62d6d3114c01a6ffa6c2ae7da5
   subdir:   c-expr-dsl
   --sha256: 19dbw858gz8hfvz677r78f9ly2h03sq0lc479wqjdydfk6i4v2wn
