{-# LANGUAGE CPP                   #-}
{-# LANGUAGE DerivingVia           #-}
{-# LANGUAGE LambdaCase            #-}
{-# LANGUAGE OverloadedLists       #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE RecursiveDo           #-}
{-# LANGUAGE TypeFamilies          #-}

{-# OPTIONS_GHC -Wno-partial-type-signatures #-}

-- |
-- Module      : Distribution.HsBindgen.Hooks
-- Description : Cabal Setuphooks for HsBindgen
-- Copyright   : (c) Samuli Thomasson, 2026
--
-- Maintainer  : Samuli Thomasson <samuli.thomasson@pm.me>
-- Stability   : unstable
-- Portability : unportable
--
module Distribution.HsBindgen.Hooks
  ( HsBindGen(..)
  , BSpec(..)
  , ExtBindingSpec(..)
  , makeBindingSpec
  , genBindingSpec
  , MkBindRules(..)
  , PCRE
  , ToPCRE(..)

  -- * Setup hooks
  , bindgenHooks
  , bindgenPreConfPackageHook
  , bindgenPreConfComponentHook
  , bindgenPreBuildComponentRules

  -- * Action
  , bindgenRule
  , createBindingsCommand

  -- * Re-exports
  , ModuleName
  , Default(..)
  )
    where

import           Distribution.HsBindgen.Utils
import           Distribution.HsBindgen.Types

import           Distribution.Compat.Binary
import           Distribution.Simple.LocalBuildInfo
import           Distribution.Simple.Program
import           Distribution.Simple.Setup
import           Distribution.Simple.SetupHooks
import           Distribution.Simple.SetupHooks.Rule
import           Distribution.Simple.Utils
import           Distribution.ModuleName
import qualified Distribution.Types.BuildInfo.Lens as BI
import           Distribution.Types.Library (explicitLibModules)
import qualified Distribution.Types.Library.Lens as Lib
import qualified Distribution.Types.LocalBuildConfig as LBC
import           Distribution.Utils.Path

import           Control.Monad
import           Control.Monad.IO.Class
import           Data.Default
import qualified Data.List.NonEmpty as NE
import qualified Data.Map as M
import           Data.Maybe
import           Distribution.Pretty
import           GHC.Generics (Generic)
import           GHC.Stack
import           Lens.Micro
import           Lens.Micro.GHC ()
import           System.Directory (doesFileExist)
import qualified System.FilePath as FP

getModuleName :: HsBindGen -> ModuleName
getModuleName x = fromFlagOrDefault "Generated" x.moduleName

-- | Names of the modules that ought to be generated (depends on configuration which files are generated).
bindGenModules :: HsBindGen -> [ModuleName]
bindGenModules spec =
  [ mname ] ++
  [ mname `suf` "FunPtr" | Flag False /= spec.hasPointer ] ++
  [ mname `suf` "Safe"   | Flag False /= spec.hasSafe ] ++
  [ mname `suf` "Unsafe" | Flag False /= spec.hasUnsafe ] ++
  [ mname `suf` "Global" | Flag False /= spec.genGlobal ]
    where
      mname = getModuleName spec
      suf mo x = fromString $ prettyShow mo <.> x

-- | File names of the generated bindings modules.
bindingsModulePaths :: HsBindGen -> [RelativePath Source 'File]
bindingsModulePaths spec = [ moduleNameSymbolicPath mo <.> "hs" | mo <- bindGenModules spec ]

-- | Manually crafted binding specification file.
makeBindingSpec :: FilePath -> ExtBindingSpec
makeBindingSpec path =
  -- ?? findAndMonitorDirFileGlob
  BFile $ makeRelativePathEx $ "binding-specs" </> path <.> "yaml"

-- | Reference to a spec file (to be) generated by hs-bindgen-cli
genBindingSpec :: ModuleName -> RelativePath Source 'File
genBindingSpec nm = makeRelativePathEx $ prettyShow nm <.> "yaml"

-- * MkBindRules

-- | Class of hooks configuration objects that should be followed up with hs-bindgen rules.
-- TODO refactor
class MkBindRules a where

  -- | At configure step: get the bindgen targets for package description.
  bindTargets :: PreConfComponentInputs -> a -> IO [HsBindGen]

  -- | At build time: get bindgen targets and any dependant rules.
  mkBindRules :: PreBuildComponentInputs
              -> [(HsBindGen, [Dependency])] -- fixed-point
              -> a
              -> RulesM [(HsBindGen, [Dependency])]

-- | Run a simple set of hs-bindgen hooks only.
instance MkBindRules [HsBindGen] where
  bindTargets _ = return
  mkBindRules _ _ xs = pure [ (x, []) | x <- xs ]

-- SetupHooks

bindgenHooks :: MkBindRules a => a -> SetupHooks
bindgenHooks cfg = mempty
  { configureHooks = mempty
    { preConfPackageHook = Just bindgenPreConfPackageHook
    , preConfComponentHook = Just $ bindgenPreConfComponentHook cfg }
  , buildHooks = mempty
    { preBuildComponentRules = Just $ bindgenPreBuildComponentRules cfg }
  }

bindgenPreConfPackageHook :: PreConfPackageInputs -> IO PreConfPackageOutputs
bindgenPreConfPackageHook inputs@PreConfPackageInputs{configFlags=flags, localBuildConfig=lbc} = do
  configured <- configurePrograms v [ "hs-bindgen-cli" ] (LBC.withPrograms lbc)
  return (noPreConfPackageOutputs inputs) { extraConfiguredProgs = configured }
  where
    v = verbosityFromFlags $ fromFlag $ setupVerbosity $ configCommonFlags flags

bindgenPreConfComponentHook :: MkBindRules a => a -> PreConfComponentInputs -> IO PreConfComponentOutputs
bindgenPreConfComponentHook setup pci
  | CLib lib <- pci.component
  = do
    specs <- bindTargets pci setup
    return $ (noPreConfComponentOutputs pci) { componentDiff = ComponentDiff $ doLib specs lib }
  | otherwise = return (noPreConfComponentOutputs pci)
  where
    doLib specs lib = CLib $ mempty
      & BI.autogenModules  .~ filter (`notElem` autogenModulesOld) genmodules
      & BI.otherModules    .~ filter (not . exposed) undeclaredModules
      & Lib.exposedModules .~ filter exposed undeclaredModules
      where
        genmodules = concatMap bindGenModules specs
        autogenModulesOld = lib ^. BI.autogenModules
        undeclaredModules = filter (`notElem` explicitLibModules lib) genmodules
        exposed _  = True -- XXX: should autogenerated module be exposed or not?

bindgenPreBuildComponentRules :: MkBindRules a => a -> Rules PreBuildComponentInputs
bindgenPreBuildComponentRules cfg = rules (static ()) (buildRules cfg)

-- * Build

buildRules :: HasCallStack => MkBindRules a => a -> PreBuildComponentInputs -> RulesM ()
buildRules cfg inputs = do
  (bindgen, _) <- liftIO $ requireProgram v hsBindgenProgram (withPrograms inputs.localBuildInfo)
  mdo
    specs <- mkBindRules inputs specs cfg
    results <- forM (M.fromList [(getModuleName spec, x) | x@(spec, _) <- specs]) $ \(spec, extraDeps) -> do
      let args = PreProcessArgs
            { verbosityFlags    = buildingWhatVerbosity inputs.buildingWhat
            , bindgenCwd        = buildingWhatWorkingDir inputs.buildingWhat
            , genBindingSpecDir = buildDir inputs.localBuildInfo </> makeRelativePathEx "binding-specs"
            , bindgenOptions    = spec
            , bindgenProgram    = bindgen
            , hsOutputDir       = autogendir
            }
      bindgenRule args inputs (fmap fst results) extraDeps

    liftIO $ forM_ results $ \(rid, s) -> infoNoWrap v $ "==== bindgen rule: " ++ prettyShow rid ++ "\n" ++ s
  where
    v          = verbosityFromFlags $ buildingWhatVerbosity inputs.buildingWhat
    autogendir = autogenComponentModulesDir inputs.localBuildInfo (targetCLBI inputs.targetInfo)

bindgenRule
  :: PreProcessArgs
  -> PreBuildComponentInputs
  -> M.Map ModuleName RuleId -- ^ memoized rules for dependencies
  -> [Dependency]
  -> RulesM (RuleId, String)
bindgenRule args pbci done extraDeps = do
  rid <- registerRule rname $ staticRule (createBindingsCommand args) deps results
  return (rid, unlines $ map prettyShow deps)
  where
    spec = args.bindgenOptions
    rname = fromString $ prettyShow $ getModuleName spec
    deps =
      [ FileDependency loc | PrescriptiveBSpec loc <- flagToList spec.bindingSpec ]
      ++ map extBSpecDependency spec.extBindingSpecs
      ++ extraDeps
        where
          extBSpecDependency = \case
            BModule nm Nothing    -> RuleDependency $ RuleOutput (done ^. at nm . non (error $ "no key for module: " ++ prettyShow nm)) 0 -- XXX
            BModule nm (Just dir) -> FileDependency $ Location dir (makeRelativePathEx $ prettyShow nm ++ ".yaml")
            BFile file            -> FileDependency $ Location (makeSymbolicPath $ packageRoot $ buildingWhatCommonFlags pbci.buildingWhat) file
            BFileLocation loc     -> FileDependency loc

    -- 0-1x generated binding spec output (when applicable)
    -- 1-5x hs-bindgen results files (.hs)
    results = NE.fromList $
      [ fromMaybe defRes mf | GenerateBSpec mf <- pure $ fromFlagOrDefault def args.bindgenOptions.bindingSpec ]
      ++ map (Location args.hsOutputDir) (bindingsModulePaths args.bindgenOptions)
        where
          defRes = Location args.genBindingSpecDir (genBindingSpec $ getModuleName args.bindgenOptions)


data PreProcessArgs = PreProcessArgs
  { verbosityFlags    :: VerbosityFlags
  , bindgenCwd        :: Maybe (SymbolicPath CWD ('Dir Pkg))
  , bindgenProgram    :: ConfiguredProgram
  , hsOutputDir       :: SymbolicPath Pkg (Dir Source) -- ^ Where to write .hs files
  , genBindingSpecDir :: SymbolicPath Pkg (Dir Source) -- ^ Where to store generated binding specs (.yaml)
  , bindgenOptions    :: HsBindGen
  } deriving (Eq, Show, Generic, Binary)

createBindingsCommand :: PreProcessArgs -> Command PreProcessArgs (IO ())
createBindingsCommand = mkCommand (static Dict) (static createBindings)

createBindings :: PreProcessArgs -> IO ()
createBindings PreProcessArgs{ bindgenOptions = gen, .. } = do
  noticeNoWrap verb $ "Generating bindings for " ++ prettyShow mname ++ "..."
  runProgramCwd verb bindgenCwd bindgenProgram $
    [ "-v", show $ verbosityLevelInt verb ] ++
    [ "preprocess" ] ++
    [ "-I" <> dir | dir <- includeSearchDirs ] ++
    [ "--clang-option-before", "-std=" ++ fromFlagOrDefault "gnu23" gen.cStandard ] ++
    [ "--external-binding-spec=" ++ file | file <- externalBindingSpecs ] ++
    [ "--select-from-main-header-dirs"     | Flag True == gen.selectFromMainHeaderDirs ] ++
    [ "--select-except-deprecated"         | Flag True /= gen.selectDeprecated ] ++
    [ "--select-except-by-decl-name=" ++ x | arg@(PCRE x) <- pure gen.excludeByDeclName, arg /= mempty ] ++
    [ "--select-except-by-header-path=" ++ x | arg@(PCRE x) <- pure gen.excludeHeaders, arg /= mempty ] ++
    [ "--enable-program-slicing"           | Flag True == gen.programSlicing ] ++
    [ "--omit-field-prefixes"              | Flag False /= gen.omitFieldPrefixes ] ++
    [ "--unique-id=" <> fromFlagOrDefault mkUniqueId gen.uniqueId ] ++
    [ "--module=" <> prettyShow mname ] ++
    [ "--hs-output-dir=" <> interpretSymbolicPathCWD hsOutputDir ] ++
    [ mkBSpec gen.bindingSpec ] ++
    [ "--create-output-dirs" ] ++
    [ "--overwrite-files" ] ++
    gen.extraArgs ++ "--" : map (interpretSymbolicPathCWD . normaliseSymbolicPath . location) gen.headers
  mapM_ (ensureHsModuleOutput verb (interpretSymbolicPath bindgenCwd hsOutputDir)) (bindGenModules gen)
  where
    verb              = verbosityFromFlags verbosityFlags
    mname             = getModuleName gen
    includeSearchDirs = interpretSymbolicPathCWD hsOutputDir : map interpretSymbolicPathCWD gen.includeDirs

    externalBindingSpecs = gen.extBindingSpecs >>= \case
        BFile file                 -> pure $ interpretSymbolicPathCWD file
        BFileLocation loc          -> pure $ interpretSymbolicPathCWD (location loc)
        BModule modname Nothing    -> pure . interpretSymbolicPathCWD $ genBindingSpecDir </> genBindingSpec modname
        BModule modname (Just dir) -> pure . interpretSymbolicPathCWD $ dir </> genBindingSpec modname

    mkBSpec = \case
      Flag (PrescriptiveBSpec loc)    -> "--prescriptive-binding-spec=" ++ interpretSymbolicPathCWD (location loc)
      Flag (GenerateBSpec (Just loc)) -> "--gen-binding-spec=" ++ interpretSymbolicPathCWD (location loc)
      _                               -> "--gen-binding-spec=" ++ interpretSymbolicPathCWD (genBindingSpecDir </> genBindingSpec mname)

    mkUniqueId = filter (`elem` (['a'..'z'] :: String)) $ prettyShow mname

ensureHsModuleOutput :: Verbosity -> FilePath -> ModuleName -> IO ()
ensureHsModuleOutput v dir modname = do
  done <- doesFileExist filepath
  unless done $ do
      warn v $ "Creating expected output file, because hs-bindgen-cli did not: " ++ filepath
      createDirectoryIfMissingVerbose v True (FP.takeDirectory filepath)
      rewriteFileEx v filepath $ "module " ++ prettyShow modname ++ " where"
  where
    filepath = dir </> toFilePath modname <.> "hs"

hsBindgenProgram :: Program
hsBindgenProgram = simpleProgram "hs-bindgen-cli"
