{-# LANGUAGE CPP                 #-}
{-# LANGUAGE DerivingStrategies  #-}
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedLists     #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE RecursiveDo #-}


{-# OPTIONS_GHC -Wno-partial-type-signatures #-}

-- |
-- Module      : Distribution.HsBindgen.Hooks
-- Description : Cabal Setuphooks for HsBindgen
-- Copyright   : (c) Samuli Thomasson, 2026
--
-- Maintainer  : Samuli Thomasson <samuli.thomasson@pm.me>
-- Stability   : unstable
-- Portability : unportable
--
module Distribution.HsBindgen.Hooks
  ( HsBindGenSetup(..)
  , HsBindGen(..)
  , BSpec(..)
  , ExtBindingSpec(..)
  , makeBindingSpec
  , MkBindRules(..)

  -- * Setup hooks
  , hsBindgenSetupHooks

  -- * Action
  -- static pointer, must export
  , preBuildRules
  , mkBindgenRule

  -- * Re-exports
  , ModuleName
  , Default(..)
  )
    where

import           Distribution.HsBindgen.Utils

import           Distribution.Compat.Binary
import           Distribution.Compat.Lens
import           Distribution.Simple.LocalBuildInfo
import           Distribution.Simple.Program
import           Distribution.Simple.Setup
import           Distribution.Simple.SetupHooks
import           Distribution.Simple.Utils
--import           Distribution.Simple.Build.Inputs
import qualified Distribution.Types.BuildInfo.Lens as BI
import           Distribution.Types.Library (explicitLibModules)
import qualified Distribution.Types.Library.Lens as Lib
import qualified Distribution.Types.LocalBuildConfig as LBC
import           Distribution.Utils.Path
import           Distribution.ModuleName
import           Distribution.Pretty (prettyShow)

import qualified Data.List.NonEmpty as NE
import           System.Directory (doesFileExist)
import           Control.Monad
import           Control.Applicative
import           Control.Monad.IO.Class
import           Data.Default
import           Data.Foldable
import qualified Data.Map as M
import           GHC.Generics (Generic)
import qualified System.FilePath as FP
import Data.Monoid

-- HsBindGenSetup

data HsBindGenSetup a = HsBindGenSetup
  { modulesSimple :: [HsBindGen]
  , sources       :: [a]
  } deriving stock (Show, Generic)

instance Default (HsBindGenSetup a) where
  def = HsBindGenSetup [] []

-- SetupHooks

hsBindgenSetupHooks :: MkBindRules a => HsBindGenSetup a -> SetupHooks
hsBindgenSetupHooks setup =
  preBindgenHooks setup.sources <>
  mempty
  { configureHooks = mempty
    { preConfPackageHook = Just hsBindgenPackagePreConf
    , preConfComponentHook = Just $ hsBindgenComponentPreConf setup }
  , buildHooks = mempty
    { preBuildComponentRules = Just $ preBuildRules setup }
  }

-- Pre-Configure

hsBindgenPackagePreConf :: PreConfPackageInputs -> IO PreConfPackageOutputs
hsBindgenPackagePreConf inputs@PreConfPackageInputs{configFlags=flags, localBuildConfig=lbc} = do
  configured <- configurePrograms v [ "hs-bindgen-cli" ] (LBC.withPrograms lbc)
  return (noPreConfPackageOutputs inputs) { extraConfiguredProgs = configured }
  where
    v = verbosityFromFlags $ fromFlag $ setupVerbosity $ configCommonFlags flags

hsBindgenComponentPreConf :: MkBindRules a => HsBindGenSetup a -> PreConfComponentInputs -> IO PreConfComponentOutputs
hsBindgenComponentPreConf setup pci
  | CLib lib <- pci.component
  = return $ (noPreConfComponentOutputs pci) { componentDiff = ComponentDiff $ doLib lib }
  | otherwise = return (noPreConfComponentOutputs pci)
  where
    specs = setup.modulesSimple ++ concatMap bindTargets setup.sources
    genmodules = concatMap bindGenModules specs
    exposed _ = True -- XXX: should autogenerated module be exposed or not?

    -- cdiff out | CLib lib <- pci.component = out { componentDiff = ComponentDiff . CLib $ doLib lib }
    --           | otherwise                 = out

    doLib lib = CLib $ mempty
      & BI.autogenModules  .~ filter (`notElem` autogenModulesOld) genmodules
      & BI.otherModules    .~ filter (not . exposed) undeclaredModules
      & Lib.exposedModules .~ filter exposed undeclaredModules
      where
        autogenModulesOld = lib ^. BI.autogenModules
        explModules = explicitLibModules lib
        undeclaredModules = filter (`notElem` explModules) genmodules

-- PreBuild

preBuildRules :: MkBindRules a => HsBindGenSetup a -> Rules PreBuildComponentInputs -- -> RulesM ()
preBuildRules setup = rules (static ()) $ \inputs -> do
    xs <- mkBindRules inputs setup.sources
    buildRules (map (, []) setup.modulesSimple <> xs) inputs

buildRules :: [(HsBindGen, [Dependency])] -> PreBuildComponentInputs -> RulesM ()
buildRules specs pbci = mdo
  (bindgen, _) <- liftIO $ requireProgram verb hsBindgenProgram (withPrograms pbci.localBuildInfo)
  results <- forM (M.fromList [(spec.moduleName, x) | x@(spec, _) <- specs]) $
    \(spec, extraDeps) ->
        registerRule (fromString $ prettyShow spec.moduleName) $
          mkBindgenRule vflags bindgen autogendir results spec extraDeps
  return ()
  where
    vflags     = buildingWhatVerbosity pbci.buildingWhat
    verb       = verbosityFromFlags vflags
    autogendir = autogenComponentModulesDir pbci.localBuildInfo (targetCLBI pbci.targetInfo)

mkBindgenRule :: VerbosityFlags
              -> ConfiguredProgram
              -> SymbolicPath Pkg (Dir Source)
              -> M.Map ModuleName RuleId
              -> HsBindGen
              -> [Dependency]
              -> Rule
mkBindgenRule verbosityFlags bindgenProgram hsOutputDir done spec staticDeps =
  dynamicRule (static Dict)
    (mkCommand (static Dict) (static computeDepsAction) (done, spec))
    (mkCommand (static Dict) (static createBindings) args)
    staticDeps results
  where
    args = PreProcessArgs{ bindgenOptions = fixup spec, ..}

    -- 0-1x generated binding spec output (when applicable)
    -- 1-5x hs-bindgen results files (.hs)
    results = Location hsOutputDir (genBindingSpec spec.moduleName) NE.:|
      map (Location hsOutputDir) (bindingsModulePaths spec)

    genBindingSpecDir = hsOutputDir

    fixup = appEndo $
      Endo (\x -> if x.uniqueId == "" then mkUniqueId x else x) <>
      Endo (\x -> if x.cStandard == "" then setCStd x else x)

    mkUniqueId x = x { uniqueId  = filter (`elem` (['a'..'z'] :: String)) $ prettyShow x.moduleName }
    setCStd x    = x { cStandard = (def :: HsBindGen).cStandard }

-- | Dynamic rule dependencies:
--
-- - Binding specs: static file (when 'BFile') or rule (when 'BModule') dependencies.
computeDepsAction :: (_, HsBindGen) -> IO ([Dependency], ())
computeDepsAction (done, spec) = do
  let deps = spec.extBindingSpecs >>= \case
        BFile loc -> pure $ FileDependency loc
        BModule nm -> pure $ RuleDependency $ RuleOutput (done M.! nm) 0
  return (deps, ())

-- * MkBindRules

-- | Class of hooks configuration objects that should be followed up with hs-bindgen rules.
class MkBindRules a where
  -- | Additional setup hooks to run prior to the hs-bindgen hooks
  preBindgenHooks :: [a] -> SetupHooks
  preBindgenHooks _ = mempty

  -- | For configure step.
  bindTargets :: a -> [HsBindGen]

  -- | For build step.
  mkBindRules :: Traversable t => PreBuildComponentInputs -> t a -> RulesM [(HsBindGen, [Dependency])]

-- | Run a simple set of hs-bindgen hooks only.
instance MkBindRules HsBindGen where
  bindTargets = return
  mkBindRules _ xs = return [ (x, mempty) | x <- toList xs ]

-- | Settings for a hs-bindgen-cli invocation.
data HsBindGen = HsBindGen
  { headers                        :: [SymbolicPath Include 'File] -- ^ Header files
  , moduleName                     :: ModuleName -- ^ Output module name
  , uniqueId                       :: String
  , omitFieldPrefixes              :: Maybe Bool
  , programSlicing                 :: Maybe Bool
  , cStandard                      :: String
  , genGlobal                      :: Maybe Bool
  , extBindingSpecs                :: [ExtBindingSpec]
  , bindingSpec                    :: BSpec
  , selectDeprecated               :: Maybe Bool
  , selectFromMainHeaderDirs       :: Maybe Bool
  , excludeByDeclName              :: String -- ^ PCRE
  , extraArgs                      :: [String]  -- ^ Arbitrary additional arguments for @hs-bindgen-cli@
  , includeDirs                    :: [SymbolicPath Pkg ('Dir Include)] -- ^ Include search directories (@-I@)
  , hasPointer, hasSafe, hasUnsafe :: Bool
  , excludeHeaders                 :: [SymbolicPath Include 'File]
  } deriving (Eq, Ord, Show, Generic, Binary)

instance Monoid HsBindGen where
  mempty = HsBindGen [] "" "" Nothing Nothing "" Nothing [] (GenerateBSpec Nothing) Nothing Nothing "" [] [] True True True []

-- | Almost as 'mempty' but a couple pre-filled defaults.
instance Default HsBindGen where
  def = mempty
    { moduleName = "Generated"
    , omitFieldPrefixes = Just True
    , cStandard = "gnu23"
    , genGlobal = Just True
    }

instance Semigroup HsBindGen where
  a <> b = HsBindGen
    { headers                  = a.headers ++ b.headers
    , moduleName               = nonEmpty "" moduleName
    , uniqueId                 = nonEmpty "" uniqueId
    , omitFieldPrefixes        = altr omitFieldPrefixes
    , programSlicing           = altr programSlicing
    , cStandard                = nonEmpty "" cStandard
    , genGlobal                = altr genGlobal
    , extBindingSpecs          = a.extBindingSpecs ++ b.extBindingSpecs
    , bindingSpec              = if a.bindingSpec == bindingSpec mempty then b.bindingSpec else a.bindingSpec
    , selectDeprecated         = altr selectDeprecated
    , selectFromMainHeaderDirs = altr selectFromMainHeaderDirs
    , excludeByDeclName        = orPCRE excludeByDeclName
    , extraArgs                = a.extraArgs ++ b.extraArgs
    , includeDirs              = a.includeDirs ++ b.includeDirs
    , hasPointer               = b.hasPointer
    , hasSafe                  = b.hasSafe
    , hasUnsafe                = b.hasUnsafe
    , excludeHeaders           = a.excludeHeaders ++ b.excludeHeaders
    } where
      nonEmpty :: Eq a => a -> (HsBindGen -> a) -> a
      nonEmpty em f = if f a == em then f b else f a

      altr f = f b <|> f a

      orPCRE f
        | f a == "" = f b
        | f b == "" = f a
        | otherwise = "(" ++ f a ++ ")|(" ++ f b ++ ")"

-- | Names of the modules that ought to be generated (depends on configuration which files are generated).
bindGenModules :: HsBindGen -> [ModuleName]
bindGenModules spec =
  [ spec.moduleName ] ++
  [ spec.moduleName `suf` "FunPtr" | spec.hasPointer ] ++
  [ spec.moduleName `suf` "Safe"   | spec.hasSafe ] ++
  [ spec.moduleName `suf` "Unsafe" | spec.hasUnsafe ] ++
  [ spec.moduleName `suf` "Global" | Just False /= spec.genGlobal ]
    where
      suf mo x = fromString $ prettyShow mo <.> x

-- | File names of the generated bindings modules.
bindingsModulePaths :: HsBindGen -> [RelativePath Source 'File]
bindingsModulePaths spec = [ moduleNameSymbolicPath mo <.> "hs" | mo <- bindGenModules spec ]

-- * BindingSpec

-- | External binding spec (file or module reference)
data ExtBindingSpec
  = BFile !Location -- ^ File reference (static)
  | BModule !ModuleName -- ^ Produced by another hs-bindgen-cli instance
  deriving (Eq, Ord, Show, Generic, Binary)

-- | Prescriptive or generated binding spec for the current module?
data BSpec
  = GenerateBSpec !(Maybe Location) -- ^ Generate the spec on build and write it to the given location (or use the default if empty)
  | PrescriptiveBSpec !Location -- ^ Prescriptive spec from a file (must exist). No spec generation.
  deriving (Eq, Ord, Show, Generic, Binary)

-- | Manually crafted binding specification file.
makeBindingSpec :: FilePath -> ExtBindingSpec
makeBindingSpec path = BFile $ Location sameDirectory $ makeRelativePathEx $ "binding-specs" </> path <.> "yaml"

-- | Reference to a spec file (to be) generated by hs-bindgen-cli
genBindingSpec :: ModuleName -> RelativePath Source 'File
genBindingSpec nm = makeRelativePathEx $ "bindgen" </> prettyShow nm <.> "yaml"

data PreProcessArgs = PreProcessArgs
  { verbosityFlags    :: VerbosityFlags
  , bindgenProgram    :: ConfiguredProgram
  , bindgenOptions    :: HsBindGen
  , hsOutputDir       :: SymbolicPath Pkg (Dir Source) -- ^ Where to write .hs files
  , genBindingSpecDir :: SymbolicPath Pkg (Dir Source) -- ^ Where to store generated binding specs (.yaml)
  } deriving (Eq, Show, Generic, Binary)

createBindings :: PreProcessArgs -> () -> IO ()
createBindings PreProcessArgs{ bindgenOptions = gen, .. } _ = do
  noticeNoWrap verb $ "Generating bindings for " ++ prettyShow gen.moduleName ++ "..."
  runProgram verb bindgenProgram $
    [ "-v", show $ verbosityLevelInt verb + 1 ] ++
    -- [ "--log-enable-macro-warnings" ] ++
    -- [ "--log-squashed-as-notice" ]
    [ "preprocess" ] ++
    [ "-I" ++ dir | dir <- includeSearchDirs ] ++
    [ "--clang-option-before", "-std=" ++ gen.cStandard ] ++
    [ "--external-binding-spec=" ++ file | file <- externalBindingSpecs ] ++
    [ "--select-from-main-header-dirs"     | Just True == gen.selectFromMainHeaderDirs ] ++
    [ "--select-except-deprecated"         | Just True /= gen.selectDeprecated ] ++
    [ "--select-except-by-decl-name=" ++ x | x <- pure gen.excludeByDeclName, x /= "" ] ++
    [ "--select-except-by-header-path=" ++ x | arg <- gen.excludeHeaders, let x = getSymbolicPath arg ] ++
    [ "--enable-program-slicing"           | Just True <- pure gen.programSlicing ] ++
    [ "--omit-field-prefixes"              | Just True <- pure gen.omitFieldPrefixes ] ++
    [ "--unique-id=" ++ gen.uniqueId ] ++
    [ "--module=" ++ prettyShow gen.moduleName ] ++
    [ "--hs-output-dir=" ++ interpretSymbolicPathCWD hsOutputDir ] ++
    [ mkBSpec gen.bindingSpec ] ++
    [ "--create-output-dirs" ] ++
    [ "--overwrite-files" ] ++
    gen.extraArgs ++
    "--" : map getSymbolicPath gen.headers
  ensureHsModuleOutput verb (interpretSymbolicPathCWD hsOutputDir) gen.moduleName
  where
    verb = verbosityFromFlags verbosityFlags
    includeSearchDirs = interpretSymbolicPathCWD hsOutputDir : map interpretSymbolicPathCWD gen.includeDirs
    externalBindingSpecs = gen.extBindingSpecs >>= \case
        BFile file      -> pure . interpretSymbolicPathCWD $ location file
        BModule modname -> pure . interpretSymbolicPathCWD $ genBindingSpecDir </> genBindingSpec modname
    mkBSpec = \case
      GenerateBSpec (Just loc) -> "--gen-binding-spec=" ++ interpretSymbolicPathCWD (location loc)
      GenerateBSpec Nothing    -> "--gen-binding-spec=" ++ interpretSymbolicPathCWD (genBindingSpecDir </> genBindingSpec gen.moduleName)
      PrescriptiveBSpec loc    -> "--prescriptive-binding-spec=" ++ interpretSymbolicPathCWD (location loc)

ensureHsModuleOutput :: Verbosity -> FilePath -> ModuleName -> IO ()
ensureHsModuleOutput v dir modname = do
  done <- doesFileExist filepath
  unless done $ do
      createDirectoryIfMissingVerbose v True (FP.takeDirectory filepath)
      rewriteFileEx v filepath $ "module " ++ prettyShow modname ++ " where"
  where
    filepath = dir </> toFilePath modname <.> "hs"

hsBindgenProgram :: Program
hsBindgenProgram = simpleProgram "hs-bindgen-cli"
