{-# LANGUAGE CPP                   #-}
{-# LANGUAGE DerivingVia           #-}
{-# LANGUAGE LambdaCase            #-}
{-# LANGUAGE OverloadedLists       #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE RecursiveDo           #-}
{-# LANGUAGE TypeFamilies          #-}

{-# OPTIONS_GHC -Wno-partial-type-signatures #-}

-- |
-- Module      : Distribution.HsBindgen.Hooks
-- Description : Cabal Setuphooks for HsBindgen
-- Copyright   : (c) Samuli Thomasson, 2026
--
-- Maintainer  : Samuli Thomasson <samuli.thomasson@pm.me>
-- Stability   : unstable
-- Portability : unportable
--
module Distribution.HsBindgen.Hooks
  ( HsBindGen(..)
  , BSpec(..)
  , ExtBindingSpec(..)
  , makeBindingSpec
  , genBindingSpec
  , MkBindRules(..)
  , PCRE
  , ToPCRE(..)
  , newHsBindGen

  -- * Setup hooks
  , bindgenHooks
  , bindgenPreConfPackageHook
  , bindgenPreConfComponentHook
  , bindgenPreBuildComponentRules
  , mkBindGenRules

  -- * Action
  , createBindingsCommand

  -- * Re-exports
  , ModuleName
  , Default(..)
  , module Distribution.HsBindgen.Utils
  )
    where

import           Distribution.HsBindgen.Utils
import           Distribution.HsBindgen.Types

import           Distribution.Compat.Binary
import           Distribution.Simple.LocalBuildInfo
import           Distribution.Simple.Program
import           Distribution.Simple.Setup
import           Distribution.Simple.SetupHooks
import           Distribution.Simple.Utils
import           Distribution.ModuleName
import qualified Distribution.Types.BuildInfo.Lens as BI
import           Distribution.Types.Library (explicitLibModules)
import qualified Distribution.Types.Library.Lens as Lib
import qualified Distribution.Types.LocalBuildConfig as LBC
import           Distribution.Utils.Path
import           Distribution.Verbosity

import           Control.Monad
import           Control.Monad.IO.Class
import           Data.Default
import qualified Data.List.NonEmpty as NE
import qualified Data.Map as M
import           Data.Maybe
import           Distribution.Pretty
import           GHC.Generics (Generic)
import           GHC.Stack
import           Lens.Micro.GHC ()
import           System.Directory (doesFileExist)
import qualified System.FilePath as FP

-- | Initialize bindgen with module name.
--
-- @newHsBindGen "My.Binds" [ "my.h" ]@
newHsBindGen :: ModuleName -> [Location] -> HsBindGen
newHsBindGen mo hdrs = mempty & moduleName .~ toFlag mo & headers .~ hdrs

getModuleName :: HsBindGen -> ModuleName
getModuleName x = fromFlagOrDefault "Generated" x.moduleName

-- | Names of the modules that ought to be generated (depends on configuration which files are generated).
getModuleNames :: HsBindGen -> [ModuleName]
getModuleNames spec =
  [ mname ] ++
  [ mname `suf` "FunPtr" | fromFlagOrDefault True spec.hasPointer ] ++
  [ mname `suf` "Safe"   | fromFlagOrDefault True spec.hasSafe ] ++
  [ mname `suf` "Unsafe" | fromFlagOrDefault True spec.hasUnsafe ] ++
  [ mname `suf` "Global" | fromFlagOrDefault True spec.genGlobal ]
    where
      mname = getModuleName spec
      suf mo x = fromString $ prettyShow mo <.> x

-- | File names of the generated bindings modules.
bindingsModulePaths :: HsBindGen -> [RelativePath Source 'File]
bindingsModulePaths spec = [ moduleNameSymbolicPath mo <.> "hs" | mo <- getModuleNames spec ]

-- | Reference to a spec file (to be) generated by hs-bindgen-cli
genBindingSpec :: ModuleName -> RelativePath Source 'File
genBindingSpec nm = makeRelativePathEx $ prettyShow nm <.> "yaml"

-- | Manually crafted binding specification file.
makeBindingSpec :: FilePath -> ExtBindingSpec
makeBindingSpec path = BFile $ makeRelativePathEx $ "binding-specs" </> path <.> "yaml"

-- SetupHooks

bindgenHooks :: [HsBindGen] -> SetupHooks
bindgenHooks specs = mempty
  { configureHooks = mempty
    { preConfPackageHook = Just bindgenPreConfPackageHook
    , preConfComponentHook = Just $ bindgenPreConfComponentHook specs }
  , buildHooks = mempty
    { preBuildComponentRules = Just $ bindgenPreBuildComponentRules specs }
  }

-- | Ensure build tools exist
bindgenPreConfPackageHook :: PreConfPackageInputs -> IO PreConfPackageOutputs
bindgenPreConfPackageHook inputs@PreConfPackageInputs{configFlags=flags, localBuildConfig=lbc} = do
  configured <- configurePrograms v [ "hs-bindgen-cli" ] (LBC.withPrograms lbc)
  return (noPreConfPackageOutputs inputs) { extraConfiguredProgs = configured }
  where
    v = verbosityFromFlags $ fromFlag $ setupVerbosity $ configCommonFlags flags

-- | Configure the libraries (modules)
bindgenPreConfComponentHook :: [HsBindGen] -> PreConfComponentInputs -> IO PreConfComponentOutputs
bindgenPreConfComponentHook specs pci
  | CLib lib <- pci.component
  = do
    return $ (noPreConfComponentOutputs pci) { componentDiff = ComponentDiff $ doLib lib }
  | otherwise = return (noPreConfComponentOutputs pci)
  where
    doLib lib = CLib $ mempty
      & Lib.exposedModules .~ filter exposed undeclared
      & BI.autogenModules  .~ filter (`notElem` (lib ^. BI.autogenModules)) genmodules
      & BI.otherModules    .~ filter (not . exposed) undeclared
      where
        genmodules = concatMap getModuleNames specs
        undeclared = filter (`notElem` explicitLibModules lib) genmodules
        exposed _  = True -- XXX: should autogenerated module be exposed or not?

-- | Build rules
bindgenPreBuildComponentRules :: [HsBindGen] -> Rules PreBuildComponentInputs
bindgenPreBuildComponentRules xs = rules (static ()) $ mkBindGenRules [ (x, []) | x <- xs ]

mkBindGenRules
  :: HasCallStack
  => [(HsBindGen, [Dependency])]
  -> PreBuildComponentInputs
  -> RulesM ()
mkBindGenRules items inputs = mdo
  (bindgenProgram, _) <- liftIO $ requireProgram v hsBindgenProgram (withPrograms inputs.localBuildInfo)
  knownDeps <- forM items' $ \(bindgenSpec, extraDeps) -> do
    let args = PreProcessArgs
          { workingDirectory  = buildingWhatWorkingDir inputs.buildingWhat
          , verbosityFlags    = buildingWhatVerbosity inputs.buildingWhat
          , genBindingSpecDir = buildDir inputs.localBuildInfo </> makeRelativePathEx "binding-specs"
          , hsOutputDir       = autogenComponentModulesDir inputs.localBuildInfo (targetCLBI inputs.targetInfo)
          , .. }
    bindgenRule inputs (fmap fst knownDeps) args extraDeps
  return ()
  where
    items' = M.fromList [(getModuleName spec, x) | x@(spec, _) <- items]
    v = verbosityFromFlags $ buildingWhatVerbosity inputs.buildingWhat

-- | Class of hooks configuration objects that should be followed up with hs-bindgen rules.
-- TODO refactor
class MkBindRules a where
  -- | At build time: get bindgen targets and any dependant rules.
  mkBindRules :: PreBuildComponentInputs
              -> [(HsBindGen, [Dependency])] -- fixed-point
              -> a
              -> RulesM [(HsBindGen, [Dependency])]

-- | Run a simple set of hs-bindgen hooks only.
instance MkBindRules [HsBindGen] where
  mkBindRules _ _ xs = pure [ (x, []) | x <- xs ]

bindgenRule
  :: PreBuildComponentInputs
  -> M.Map ModuleName RuleId -- ^ memoized rules for dependencies
  -> PreProcessArgs
  -> [Dependency]
  -> RulesM (RuleId, Rule)
bindgenRule pbci done args extraDeps = do
  let rule = staticRule (createBindingsCommand args) deps results
  rid <- registerRule rname rule
  return (rid, rule)
  where
    rname = fromString $ prettyShow $ getModuleName spec
    spec  = args.bindgenSpec
    deps  = [ FileDependency loc | PrescriptiveBSpec loc <- flagToList spec.bindingSpec ]
      ++ map extBSpecDependency spec.extBindingSpecs
      ++ extraDeps

    extBSpecDependency = \case
      BModule nm Nothing    -> RuleDependency $ RuleOutput (done ^. at nm . non (error $ "no key for module: " ++ prettyShow nm)) 0 -- XXX
      BModule nm (Just dir) -> FileDependency $ Location dir (makeRelativePathEx $ prettyShow nm ++ ".yaml")
      BFile file            -> FileDependency $ Location (makeSymbolicPath $ packageRoot $ buildingWhatCommonFlags pbci.buildingWhat) file
      BFileLocation loc     -> FileDependency loc

    -- 0-1x generated binding spec output (when applicable)
    -- 1-5x hs-bindgen results files (.hs)
    results = NE.fromList $
      [ fromMaybe defRes mf | GenerateBSpec mf <- [fromFlagOrDefault def args.bindgenSpec.bindingSpec] ]
      ++ map (Location args.hsOutputDir) (bindingsModulePaths args.bindgenSpec)
    defRes = Location args.genBindingSpecDir (genBindingSpec $ getModuleName args.bindgenSpec)

data PreProcessArgs = PreProcessArgs
  { verbosityFlags    :: VerbosityFlags
  , workingDirectory  :: Maybe (SymbolicPath CWD ('Dir Pkg))
  , bindgenProgram    :: ConfiguredProgram
  , hsOutputDir       :: SymbolicPath Pkg (Dir Source) -- ^ Where to write .hs files
  , genBindingSpecDir :: SymbolicPath Pkg (Dir Source) -- ^ Where to store generated binding specs (.yaml)
  , bindgenSpec       :: HsBindGen
  } deriving (Eq, Show, Generic, Binary)

createBindingsCommand :: PreProcessArgs -> Command PreProcessArgs (IO ())
createBindingsCommand = mkCommand (static Dict) (static createBindings)

createBindings :: PreProcessArgs -> IO ()
createBindings PreProcessArgs{ bindgenSpec = gen, .. } = do
  noticeNoWrap vmore $ "[bindgen] Generating bindings for " <> prettyShow mname <> "..."
  infoNoWrap vless $ "headers: " <> show (map (FP.takeFileName . getSymbolicPath . location) gen.headers)
  noticeDoc vless $ pretty gen
  runProgramCwd vless workingDirectory bindgenProgram $
    [ "--verbosity=" <> show (verbosityLevelInt vmore) ] ++
    [ "preprocess" ] ++
    [ "--builtin-include-dir=" <> v.unwrap   | let v = fromFlagOrDefault def gen.builtinIncludeDir ] ++ -- clang / disable
    [ "-I" <> v                              | v <- prSP hsOutputDir : map prSP gen.includeDirs ] ++
    (join [[ "--hash-define", k, v ]         | (k, v) <- M.toList gen.defineMacros ]) ++
    [ "--clang-option-before=" <> v          | v <- clangBefore ] ++
    [ "--clang-option=" <> v                 | v <- clangOpts ] ++
    [ "--clang-option-after=" <> v           | v <- clangAfter ] ++
    [ "--no-stdlib"                          | fromFlagOrDefault False gen.disableStdlib ] ++
    [ "--module=" <> v                       | let v = prettyShow mname ] ++
    [ "--unique-id=" <> v                    | let v = fromFlagOrDefault defUniqId gen.uniqueId ] ++
    [ "--gen-binding-spec=" <> v             | GenerateBSpec mloc <- [fromFlagOrDefault def gen.bindingSpec], let v = interpretSymbolicPathCWD $ maybe (genBindingSpecDir </> genBindingSpec mname) location mloc ] ++
    [ "--prescriptive-binding-spec=" <> v    | PrescriptiveBSpec loc <- [fromFlagOrDefault def gen.bindingSpec], let v = interpretSymbolicPathCWD $ location loc ] ++
    [ "--external-binding-spec=" <> v        | v <- prExtBSpec <$> gen.extBindingSpecs ] ++
    [ "--select-all"                         | fromFlagOrDefault False NoFlag ] ++
    [ "--select-from-main-headers"           | fromFlagOrDefault False NoFlag ] ++
    [ "--select-from-main-header-dirs"       | fromFlagOrDefault False gen.selectFromMainHeaderDirs ] ++
    [ "--select-by-header-path=" <> v        | let arg = gen.selectHeaders,  arg /= mempty, let v = pcreValue arg ] ++
    [ "--select-except-by-header-path=" <> v | let arg = gen.excludeHeaders, arg /= mempty, let v = pcreValue arg ] ++
    [ "--select-by-decl-name=" <> v          | let arg = gen.selectDecls,    arg /= mempty, let v = pcreValue arg ] ++
    [ "--select-except-by-decl-name=" <> v   | let arg = gen.excludeDecls,   arg /= mempty, let v = pcreValue arg ] ++
    [ "--select-except-deprecated"           | not $ fromFlagOrDefault False gen.selectDeprecated ] ++
    [ "--enable-program-slicing"             | fromFlagOrDefault False gen.programSlicing ] ++
    [ "--omit-field-prefixes"                | fromFlagOrDefault True gen.omitFieldPrefixes ] ++
    [ "--overwrite-files"                    | fromFlagOrDefault True gen.overwriteFiles ] ++
    [ "--create-output-dirs"                 | fromFlagOrDefault True gen.createOutputDirs ] ++
    [ "--hs-output-dir=" <> v                | let v = interpretSymbolicPathCWD hsOutputDir ] ++
    gen.extraArgs ++ "--" : map prLoc gen.headers
  forM_ (getModuleNames gen) $ ensureHsModuleOutput vless (interpretSymbolicPath workingDirectory hsOutputDir)
  where
    vmore = verbosityFromFlags verbosityFlags
    vless = verbosityFromFlags $ lessVerbose verbosityFlags
    mname = getModuleName gen
    clangBefore = [ "-std=" <> fromFlagOrDefault "gnu23" gen.cStandard ]
    clangOpts   = []
    clangAfter  = []
    defUniqId = filter (`elem` (['a'..'z'] :: String)) $ prettyShow mname
    prExtBSpec = \case
      BFile file           -> prSP file
      BFileLocation loc    -> prLoc loc
      BModule modname mdir -> prSP $ fromMaybe genBindingSpecDir mdir </> genBindingSpec modname
    prSP  = interpretSymbolicPathCWD . normaliseSymbolicPath
    prLoc = prSP . location

ensureHsModuleOutput :: Verbosity -> FilePath -> ModuleName -> IO ()
ensureHsModuleOutput v dir modname = do
  done <- doesFileExist filepath
  unless done $ do
      warn v $ "Creating expected output file, because hs-bindgen-cli did not: " ++ filepath
      createDirectoryIfMissingVerbose v True (FP.takeDirectory filepath)
      rewriteFileEx v filepath $ "module " ++ prettyShow modname ++ " where\n"
  where
    filepath = dir </> toFilePath modname <.> "hs"

hsBindgenProgram :: Program
hsBindgenProgram = simpleProgram "hs-bindgen-cli"
