---
verbatim:
  - cabal-version:    3.12
name:               hswm
version: &version   0.1.0.0
synopsis:           Wayland window manager for River
description:        Wayland window manager for River
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
# copyright:
build-type:         Simple
tested-with:
  - GHC == 9.14.1
  - GHC == 9.12.2

flags:
  use-llvm:
    description: Link with LLVM
    default: true
    manual: true

_common-language: &language
  language: GHC2024
  default-extensions:
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedLabels
    - DuplicateRecordFields
    - OverloadedStrings
    - DerivingVia
    - DeriveAnyClass
    - PackageImports
    - QuantifiedConstraints

    # https://discourse.haskell.org/t/what-are-you-supposed-to-do-about-wambiguous-fields/9545/36?page=2
_common-ghc-options: &common-ghc-options
    -Wall
    -Wunused-packages
    -Wno-partial-type-signatures
    -Wno-ambiguous-fields

_common-rts-options: &common-rts-options
    -threaded
    -rtsopts "-with-rtsopts=-maxN4 -qn2 -A8M -K64M -M1G -kc8k"

internal-libraries:
  hswm-prelude:
    <<: *language
    source-dirs: hswm-prelude
    exposed-modules:
      - HSWM.Prelude
    other-modules: []
    dependencies:
      - &base
        name: base
        version: &base-version '>=4.21.0 && < 4.23'
      - &mtl mtl                   ^>=2.3.1
      - &stm stm                   ^>=2.5.3
      - &text text                 ^>=2.1.2
      - &data-default data-default ^>=0.8.0
      - async                      ^>=2.2.6
      - exceptions                 ^>=0.10.9
      - &rio rio                   ^>=0.1.24
      - unliftio-core              ^>=0.2.1
      - unliftio                   ^>=0.2.25
      - &monad-logger-aeson
        monad-logger-aeson         ^>=0.4.1
    ghc-options:
      - *common-ghc-options

library:
  <<: *language
  source-dirs: src
  #exposed-modules: # discovered by hpack
  other-modules: []
  generated-other-modules:
    - PackageInfo_hswm
  dependencies:
    - &base-noprelude
      name: base
      version: *base-version
      mixin:
        - hiding (Prelude)
    - &hswm-prelude
      name: hswm:hswm-prelude
      mixin:
        - (HSWM.Prelude as Prelude)
    - &bytestring
      bytestring           ^>=0.12.2
    - &containers
      containers            >=0.7      && <1.0
    - *data-default
    - *mtl
    - network              ^>=3.2.8
    - deepseq              ^>=1.5.1
    - vector               ^>=0.13.2
    - &aeson
      aeson                ^>=2.2.3
    - directory            ^>=1.3.9
    - fast-logger          ^>=3.2.6
    - process              ^>=1.6.25
    - *stm
    - *text
    - &time
      time                  >=1.14     && <2.0
    - transformers         ^>=0.6.1
    - unix                 ^>=2.8.6
    - *rio
    - &optparse-applicative
      optparse-applicative ^>=0.18.1
    - &optparse-generic
      optparse-generic     ^>=1.5
    - derive-storable      ^>=0.3.1
    - utf8-string          ^>=1.0.2
    - JuicyPixels          ^>=3.3.9
    - pretty-simple        ^>=4.1.4
    - typed-process        ^>=0.2.13
    - typerep-map          ^>=0.7.0
    - unbounded-delays     ^>=0.1.1
    - filelock             ^>=0.1.1
    - pango                ^>=0.13.12
    - hswm-bindings # Generated C bindings
    - xkbcommon-bindings
  build-tools:
    - hsc2hs:hsc2hs
  ghc-options:
    - *common-ghc-options
  when:
    - condition: flag(use-llvm) && impl(ghc >= 9.14.1)
      ghc-options: -fllvm

executables:
  hswm:
    <<: *language
    main: Main.hs
    source-dirs: app
    dependencies:
      - *base
      - *containers
      - *bytestring
      - hswm
      - hswm-bindings
    ghc-options:
      - *common-ghc-options
      - *common-rts-options
    when:
      - condition: flag(use-llvm) && impl(ghc >= 9.14.1)
        ghc-options: -fllvm

  hswmctl:
    <<: *language
    main: Main.hs
    source-dirs: app-ctl
    dependencies:
      - *base
      - *text
      - *bytestring
      - *time
      - *monad-logger-aeson
      - *aeson
      - *optparse-generic
      - *optparse-applicative
      - haskeline                   ^>=0.8.2
      - prettyprinter               ^>=1.7.1
      - prettyprinter-ansi-terminal ^>=1.1.3
      - hswm
    ghc-options:
      - *common-ghc-options
      - *common-rts-options
