---
verbatim:
  - cabal-version:    3.12

name:               hswm
version: &version   0.1.0.0
synopsis:           Wayland window manager for River
description:        Wayland window manager for River
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
# copyright:
build-type:         Simple
#extra-doc-files:    README.md
#                  CHANGELOG.md
#extra-source-files:

_common/language: &language
  language: GHC2024
  default-extensions: &default-extensions
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedLabels
    - DuplicateRecordFields
    - OverloadedStrings
    - DerivingVia
    - DeriveAnyClass
    - PackageImports
    - QuantifiedConstraints
    # https://discourse.haskell.org/t/what-are-you-supposed-to-do-about-wambiguous-fields/9545/36?page=2
  ghc-options: &common-ghc-options
    -Wall
    -Wunused-packages
    -Wno-partial-type-signatures
    -Wno-ambiguous-fields

internal-libraries:
  hswm-prelude:
    <<: *language
    source-dirs: hswm-prelude
    exposed-modules:
      - HSWM.Prelude
    other-modules: []
    dependencies:
      - name: base
        version: &base-version '>=4.21.0 && < 4.22'
      - rio
      - text
      - mtl
      - data-default
      - stm
      - monad-logger-aeson
      - unliftio-core
      - unliftio
      - exceptions
      - async

library:
  <<: *language
  source-dirs: src
  #exposed-modules: # discovered by hpack
  other-modules: []
  generated-other-modules:
    - PackageInfo_hswm
  #  - Paths_hswm
  dependencies:
    - rio
    - &base-noprelude
      name: base
      version: *base-version
      mixin:
        - hiding (Prelude)
    - &hswm-prelude
      name: hswm:hswm-prelude
      mixin:
        - (HSWM.Prelude as Prelude)
    - containers ^>=0.7
    - data-default ^>=0.8.0
    - derive-storable
    - utf8-string
    - pretty-simple
    - text
    - transformers
    - typerep-map
    - unix
    - hswm-bindings # Generated C bindings
    - directory
    - vector
    - JuicyPixels ^>=3.3.9
    - network
    - bytestring ^>=0.12.2
    - aeson
    - deepseq
    - mtl
    - stm
    - process
    - typed-process
    - xkbcommon-bindings
    - time
    - unbounded-delays
    - fast-logger
  build-tools:
    - c2hs:c2hs  # Note: may need to "cabal update for this to start working

executables:
  hswm:
    <<: *language
    main: Main.hs
    source-dirs: app
    dependencies:
      - base
      - hswm
      - hswm-bindings
      - containers
    ghc-options:
      - *common-ghc-options
      - -threaded
      - -rtsopts "-with-rtsopts=-maxN4 -qn2 -A8M -K64M -M1G -kc8k"
      #- -pie
      #- -fPIC

  hswmctl:
    <<: *language
    main: Main.hs
    source-dirs: app-ctl
    dependencies:
      - base
      - hswm
    ghc-options:
      - *common-ghc-options
      - -threaded
