{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "2.0";
      identifier = { name = "haskell-gi-base"; version = "0.26.9"; };
      license = "LGPL-2.1-only";
      copyright = "";
      maintainer = "Iñaki García Etxebarria (inaki@blueleaf.cc)";
      author = "Will Thompson,\nIñaki García Etxebarria,\nJonas Platte";
      homepage = "https://github.com/haskell-gi/haskell-gi";
      url = "";
      synopsis = "Foundation for libraries generated by haskell-gi";
      description = "Foundation for libraries generated by haskell-gi";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."text" or (errorHandler.buildDepError "text"))
          (hsPkgs."optics-core" or (errorHandler.buildDepError "optics-core"))
        ];
        pkgconfig = [
          (pkgconfPkgs."gobject-2.0" or (errorHandler.pkgConfDepError "gobject-2.0"))
          (pkgconfPkgs."glib-2.0" or (errorHandler.pkgConfDepError "glib-2.0"))
        ];
        build-tools = [
          (hsPkgs.pkgsBuildBuild.hsc2hs.components.exes.hsc2hs or (pkgs.pkgsBuildBuild.hsc2hs or (errorHandler.buildToolDepError "hsc2hs:hsc2hs")))
        ];
        buildable = true;
      };
    };
  } // {
    src = pkgs.lib.mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/haskell-gi-base-0.26.9.tar.gz";
      sha256 = "c359bbcfb06928f6b9817d4fb8f44b595382a7d405b63c2ceefed85f26c221d2";
    });
  }) // {
    package-description-override = "name:                haskell-gi-base\nversion:             0.26.9\nsynopsis:            Foundation for libraries generated by haskell-gi\ndescription:         Foundation for libraries generated by haskell-gi\nhomepage:            https://github.com/haskell-gi/haskell-gi\nlicense:             LGPL-2.1\n                     -- or above\nlicense-file:        LICENSE\nauthor:              Will Thompson,\n                     Iñaki García Etxebarria,\n                     Jonas Platte\nmaintainer:          Iñaki García Etxebarria (inaki@blueleaf.cc)\nstability:           Experimental\ncategory:            Development\nbuild-type:          Simple\ncabal-version:       2.0\n\nextra-source-files: ChangeLog.md\n\nsource-repository head\n  type: git\n  location: https://github.com/haskell-gi/haskell-gi.git\n\nlibrary\n  exposed-modules:     Data.GI.Base,\n                       Data.GI.Base.Attributes,\n                       Data.GI.Base.BasicConversions,\n                       Data.GI.Base.BasicTypes,\n                       Data.GI.Base.CallStack,\n                       Data.GI.Base.Constructible,\n                       Data.GI.Base.GArray,\n                       Data.GI.Base.GError,\n                       Data.GI.Base.GClosure,\n                       Data.GI.Base.GHashTable,\n                       Data.GI.Base.GObject,\n                       Data.GI.Base.GQuark,\n                       Data.GI.Base.GType,\n                       Data.GI.Base.GValue,\n                       Data.GI.Base.GVariant,\n                       Data.GI.Base.ManagedPtr,\n                       Data.GI.Base.GParamSpec,\n                       Data.GI.Base.Overloading,\n                       Data.GI.Base.Properties,\n                       Data.GI.Base.ShortPrelude,\n                       Data.GI.Base.Signals,\n                       Data.GI.Base.Utils,\n                       Data.GI.Base.DynVal,\n                       Data.GI.Base.Internal.CTypes\n                       Data.GI.Base.Internal.PathFieldAccess\n\n  pkgconfig-depends:   gobject-2.0 >= 2.42, glib-2.0\n  build-depends:       base >= 4.11 && < 5,\n                       bytestring,\n                       containers,\n                       text >= 1.0,\n                       optics-core >= 0.4\n\n  ghc-options: -Wall -Wno-redundant-constraints -fwarn-incomplete-patterns -Wcompat -Wno-unticked-promoted-constructors\n\n  build-tool-depends:  hsc2hs:hsc2hs\n  cc-options:          -fPIC\n  default-language:    Haskell2010\n  default-extensions:  CPP, ForeignFunctionInterface, DoAndIfThenElse, MonoLocalBinds\n  other-extensions:    TypeApplications, ScopedTypeVariables\n  c-sources:           csrc/hsgclosure.c\n";
  }