cabal-version: 3.14
-- build-type:         Custom
build-type:         Hooks
name:               haskell-wayland-core
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
tested-with:
      GHC == 9.14.1
    , GHC == 9.12.4
    , GHC == 9.12.2
extra-source-files:
      protocol/*.xml

flag pkg-config
    description: Use pkgconfig to resolve C dependencies
    manual: True
    default: True

flag build-tool-depends
    description: Use build-tool-depends for hs-bindgen-cli
    manual: True
    default: True

custom-setup
    setup-depends:
          hs-bindgen-hooks
        , base             >=4.21 && <5
        , Cabal            >=3.14 && <3.18
        , Cabal-hooks      >=3.14 && <3.18
        , microlens-ghc
        , filepath
        , string-interpolate
        , directory

common language
    default-language: GHC2024
    default-extensions:
          DuplicateRecordFields
          OverloadedStrings
          OverloadedLabels
          OverloadedRecordDot
          TemplateHaskell
          TypeFamilies
          PatternSynonyms
          LambdaCase
          DerivingVia
          DeriveAnyClass

library
    import: language
    exposed-modules:
          -- WL.Client -- ???
          WL.Core.Client
          WL.Internals.TH
          WL.Internals.Types
          WL.Internals.Utils
          WL.Util
    other-modules:
    autogen-modules:
    build-depends:
          base                 >=4.21   && <4.23
        , containers           >=0.7    && <1.0
        , data-default         >=0.8    && <0.9
        , deepseq              >=1.5.1  && <1.6
        , hashable             >=1.5.1  && <1.6
        , template-haskell     >=2.23   && <2.25
        , unix                ^>=2.8.6
        , unliftio            ^>=0.2.25
        , c-expr-runtime       >=0.1.0  && <0.2
        , hs-bindgen-runtime   >=0.1.0  && <0.2
        , hs-bindgen-hooks     ==0.1.0.0
        , pretty
    hs-source-dirs: src
    ghc-options: -Wall -Wunused-packages -fPIC

    if flag(pkg-config)
        pkgconfig-depends:
              wayland-client     >= 1.24
            , wayland-server     >= 1.24
    else
        extra-libraries:
              wayland-client
            , wayland-server

    if flag(build-tool-depends)
       build-tool-depends: hs-bindgen:hs-bindgen-cli
