version:
  hs_bindgen: 0.1.0
  binding_specification: '1.0'
hsmodule: Generated.River.XkbConfigV1
ctypes:
- headers: river-xkb-config-v1-client-protocol.h
  cname: struct river_xkb_config_v1
  hsname: River_xkb_config_v1
- headers: river-xkb-config-v1-client-protocol.h
  cname: struct river_xkb_keyboard_v1
  hsname: River_xkb_keyboard_v1
- headers: river-xkb-config-v1-client-protocol.h
  cname: struct river_xkb_keymap_v1
  hsname: River_xkb_keymap_v1
- headers: river-xkb-config-v1-client-protocol.h
  cname: enum river_xkb_config_v1_error
  hsname: River_xkb_config_v1_error
- headers: river-xkb-config-v1-client-protocol.h
  cname: enum river_xkb_config_v1_keymap_format
  hsname: River_xkb_config_v1_keymap_format
- headers: river-xkb-config-v1-client-protocol.h
  cname: struct river_xkb_config_v1_listener
  hsname: River_xkb_config_v1_listener
- headers: river-xkb-config-v1-client-protocol.h
  cname: struct river_xkb_keymap_v1_listener
  hsname: River_xkb_keymap_v1_listener
- headers: river-xkb-config-v1-client-protocol.h
  cname: enum river_xkb_keyboard_v1_error
  hsname: River_xkb_keyboard_v1_error
- headers: river-xkb-config-v1-client-protocol.h
  cname: struct river_xkb_keyboard_v1_listener
  hsname: River_xkb_keyboard_v1_listener
hstypes:
- hsname: River_xkb_config_v1
  representation: emptydata
- hsname: River_xkb_config_v1_error
  representation:
    newtype:
      constructor: River_xkb_config_v1_error
      fields:
      - unwrap
  instances:
  - CEnum
  - Eq
  - Generic
  - HasCField
  - HasFFIType
  - HasField
  - Ord
  - Prim
  - Read
  - ReadRaw
  - SequentialCEnum
  - Show
  - StaticSize
  - Storable
  - WriteRaw
- hsname: River_xkb_config_v1_keymap_format
  representation:
    newtype:
      constructor: River_xkb_config_v1_keymap_format
      fields:
      - unwrap
  instances:
  - CEnum
  - Eq
  - Generic
  - HasCField
  - HasFFIType
  - HasField
  - Ord
  - Prim
  - Read
  - ReadRaw
  - SequentialCEnum
  - Show
  - StaticSize
  - Storable
  - WriteRaw
- hsname: River_xkb_config_v1_listener
  representation:
    record:
      constructor: River_xkb_config_v1_listener
      fields:
      - finished
      - xkb_keyboard
  instances:
  - Eq
  - Generic
  - HasCField
  - HasField
  - ReadRaw
  - Show
  - StaticSize
  - Storable
  - WriteRaw
- hsname: River_xkb_keyboard_v1
  representation: emptydata
- hsname: River_xkb_keyboard_v1_error
  representation:
    newtype:
      constructor: River_xkb_keyboard_v1_error
      fields:
      - unwrap
  instances:
  - CEnum
  - Eq
  - Generic
  - HasCField
  - HasFFIType
  - HasField
  - Ord
  - Prim
  - Read
  - ReadRaw
  - SequentialCEnum
  - Show
  - StaticSize
  - Storable
  - WriteRaw
- hsname: River_xkb_keyboard_v1_listener
  representation:
    record:
      constructor: River_xkb_keyboard_v1_listener
      fields:
      - removed
      - input_device
      - layout
      - capslock_enabled
      - capslock_disabled
      - numlock_enabled
      - numlock_disabled
  instances:
  - Eq
  - Generic
  - HasCField
  - HasField
  - ReadRaw
  - Show
  - StaticSize
  - Storable
  - WriteRaw
- hsname: River_xkb_keymap_v1
  representation: emptydata
- hsname: River_xkb_keymap_v1_listener
  representation:
    record:
      constructor: River_xkb_keymap_v1_listener
      fields:
      - success
      - failure
  instances:
  - Eq
  - Generic
  - HasCField
  - HasField
  - ReadRaw
  - Show
  - StaticSize
  - Storable
  - WriteRaw
