{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "3.0";
      identifier = { name = "hs-bindgen-runtime"; version = "0.1.0"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "info@well-typed.com";
      author = "Well-Typed LLP";
      homepage = "";
      url = "";
      synopsis = "Runtime support for code generated by hs-bindgen";
      description = "This library provides abstractions used by the code generated by @hs-bindgen@.\nIn most cases it is also necessary for /interacting/ with that code. To do so,\nyou will probably want to start by importing the prelude\n\n> HsBindgen.Runtime.Prelude\n\nand then import other modules as needed; with the exception of the prelude,\nall other modules are intended for qualified import.";
      buildType = "Simple";
      isLocal = true;
      detailLevel = "FullDetails";
      licenseFiles = [ "LICENSE" ];
      dataDir = ".";
      dataFiles = [];
      extraSrcFiles = [];
      extraTmpFiles = [];
      extraDocFiles = [ "CHANGELOG.md" "CHANGELOG.md" "README.md" ];
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."primitive" or (errorHandler.buildDepError "primitive"))
          (hsPkgs."record-hasfield" or (errorHandler.buildDepError "record-hasfield"))
          (hsPkgs."template-haskell" or (errorHandler.buildDepError "template-haskell"))
          (hsPkgs."vector" or (errorHandler.buildDepError "vector"))
        ] ++ pkgs.lib.optional (compiler.isGhc && compiler.version.lt "9.4") (hsPkgs."data-array-byte" or (errorHandler.buildDepError "data-array-byte"));
        build-tools = [
          (hsPkgs.pkgsBuildBuild.hsc2hs.components.exes.hsc2hs or (pkgs.pkgsBuildBuild.hsc2hs or (errorHandler.buildToolDepError "hsc2hs:hsc2hs")))
        ];
        buildable = true;
        modules = [
          "HsBindgen/Runtime/Internal/FunPtr/Class"
          "HsBindgen/Runtime/TH/Instances"
          "HsBindgen/Runtime/TH/Types"
          "HsBindgen/Runtime/BitfieldPtr"
          "HsBindgen/Runtime/Block"
          "HsBindgen/Runtime/CBool"
          "HsBindgen/Runtime/CEnum"
          "HsBindgen/Runtime/ConstantArray"
          "HsBindgen/Runtime/FLAM"
          "HsBindgen/Runtime/HasCBitfield"
          "HsBindgen/Runtime/HasCField"
          "HsBindgen/Runtime/IncompleteArray"
          "HsBindgen/Runtime/Internal/Bitfield"
          "HsBindgen/Runtime/Internal/ByteArray"
          "HsBindgen/Runtime/Internal/CAPI"
          "HsBindgen/Runtime/Internal/Deriving"
          "HsBindgen/Runtime/Internal/FFIType"
          "HsBindgen/Runtime/Internal/FunPtr"
          "HsBindgen/Runtime/Internal/HasFFIType"
          "HsBindgen/Runtime/Internal/LibC/Auxiliary"
          "HsBindgen/Runtime/Internal/Prelude"
          "HsBindgen/Runtime/Internal/Prelude/CompatHasField"
          "HsBindgen/Runtime/Internal/Ptr"
          "HsBindgen/Runtime/Internal/SizedByteArray"
          "HsBindgen/Runtime/IsArray"
          "HsBindgen/Runtime/LibC"
          "HsBindgen/Runtime/Marshal"
          "HsBindgen/Runtime/Prelude"
          "HsBindgen/Runtime/PtrConst"
          "HsBindgen/Runtime/Union"
        ];
        hsSourceDirs = [ "src" ];
      };
      tests = {
        "test-hs-bindgen-runtime" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."hs-bindgen-runtime" or (errorHandler.buildDepError "hs-bindgen-runtime"))
            (hsPkgs."primitive" or (errorHandler.buildDepError "primitive"))
            (hsPkgs."QuickCheck" or (errorHandler.buildDepError "QuickCheck"))
            (hsPkgs."tasty" or (errorHandler.buildDepError "tasty"))
            (hsPkgs."tasty-expected-failure" or (errorHandler.buildDepError "tasty-expected-failure"))
            (hsPkgs."tasty-hunit" or (errorHandler.buildDepError "tasty-hunit"))
            (hsPkgs."tasty-quickcheck" or (errorHandler.buildDepError "tasty-quickcheck"))
            (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
          ];
          buildable = true;
          modules = [
            "Test/HsBindgen/Runtime/Bitfield"
            "Test/HsBindgen/Runtime/CBool"
            "Test/HsBindgen/Runtime/CEnum"
            "Test/HsBindgen/Runtime/CEnumArbitrary"
            "Test/HsBindgen/Runtime/ConstantArray"
            "Test/HsBindgen/Runtime/IncompleteArray"
            "Test/HsBindgen/Runtime/SizedByteArray"
            "Test/Util/Orphans"
            "Test/Util/Tasty"
          ];
          hsSourceDirs = [ "test" ];
          mainPath = [ "test-runtime.hs" ];
        };
      };
    };
  } // {
    src = pkgs.lib.mkDefault (pkgs.fetchgit {
      url = "0";
      rev = "minimal";
      sha256 = "";
    }) // {
      url = "0";
      rev = "minimal";
      sha256 = "";
    };
    postUnpack = "sourceRoot+=/hs-bindgen-runtime; echo source root reset to $sourceRoot";
  }