cabal-version: 3.14
name:               hswm-bindings
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
--build-type:         Hooks
build-type:         Custom
tested-with:
      GHC == 9.12.2
    , GHC == 9.14.1
extra-source-files:
      binding-specs/*.yaml
      protocol/*.xml
extra-doc-files:
      CHANGELOG.md

flag pkg-config
    description: Use pkgconfig to resolve C dependencies
    manual: True
    default: True

flag build-tool-depends
    description: Use build-tool-depends for hs-bindgen-cli
    manual: True
    default: True

custom-setup
    setup-depends:
          base             >=4.21 && <5
        , Cabal            >=3.14 && <3.18
        , Cabal-hooks      >=3.14 && <3.18
        , filepath
        , hs-bindgen-hooks
        , microlens
        , microlens-ghc

common language
    default-language: GHC2024
    default-extensions:
          DuplicateRecordFields
          OverloadedStrings
          OverloadedLabels
          OverloadedRecordDot
          TemplateHaskell
          TypeFamilies
          PatternSynonyms
          LambdaCase

library
    import: language
    exposed-modules:
          -- core types
          Wayland.Types
          -- code generation
          Wayland.Internal.TH
          -- Wayland protocols
          Wayland
          Wayland.Viewporter
          Bindings.Wayland.Util
          Bindings.Wayland.Client
          Bindings.Wayland.XdgShell
          Bindings.Wayland.ExtIdleNotifyV1
          Bindings.Wayland.ExtSessionLockV1
          Bindings.Wayland.FractionalScaleV1
          Bindings.Wayland.ExtForeignTopLevelListV1
          Bindings.Wayland.Viewporter
          Bindings.Wayland.XdgOutputUnstableV1
          Bindings.Wayland.TextInputUnstableV3
          -- wlroots protocols
          Bindings.Wlr.InputMethodUnstableV2
          Bindings.Wlr.LayerShellUnstableV1
          Bindings.Wlr.OutputManagementUnstableV1
          Bindings.Wlr.OutputPowerManagementUnstableV1
          -- River protocols
          River
          River.InputManagement
          River.LayerShell
          River.LibinputConfig
          River.WindowManagement
          River.XkbBindings
          River.XkbConfig
          Bindings.River
          Bindings.River.InputManagementV1
          Bindings.River.LayerShellV1
          Bindings.River.LibinputConfigV1
          Bindings.River.WindowManagementV1
          Bindings.River.XkbBindingsV1
          Bindings.River.XkbConfigV1
    other-modules:
          Paths_hswm_bindings
    autogen-modules:
          Paths_hswm_bindings
    build-depends:
          base                 >=4.21   && <4.23
        , containers
        , data-default         >=0.8    && <0.9
        , deepseq              >=1.5.1  && <1.6
        , hashable             >=1.5.1  && <1.6
        , template-haskell     >=2.23   && <2.25
        , text                 >=2.1.2  && <2.2
        , unix
        , unliftio
        , c-expr-runtime       >=0.1.0  && <0.2
        , hs-bindgen-runtime   >=0.1.0  && <0.2
        , hs-bindgen-hooks
    hs-source-dirs:
          src
    ghc-options: -Wall -Wunused-packages -fPIC

    if flag(pkg-config)
        pkgconfig-depends:
              wayland-client >= 1.24
            , wayland-server >= 1.24
            , wayland-protocols >= 1.48
    else
        extra-libraries:
              wayland-client
            , wayland-server

    if flag(build-tool-depends)
       build-tool-depends: hs-bindgen:hs-bindgen-cli

test-suite test-suite
    import: language
    type: exitcode-stdio-1.0
    other-modules:
          Paths_hswm_bindings
          Wayland.UtilSpec
    autogen-modules:
          Paths_hswm_bindings
    build-depends:
          base
        , data-default
        , hspec
        , hs-bindgen-runtime   >=0.1.0  && <0.2
        , hswm-bindings
    main-is: Spec.hs
    hs-source-dirs: tests
    build-tool-depends: hspec-discover:hspec-discover
    ghc-options: -threaded -with-rtsopts=-N
