cabal-version: 3.14
-- build-type:         Custom
build-type:         Hooks
name:               hswm-bindings
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
tested-with:
      GHC == 9.14.1
    , GHC == 9.12.4
    , GHC == 9.12.2
extra-source-files:
      protocol/*.xml
-- data-files: bindgen/*.yaml
extra-doc-files:
      CHANGELOG.md

flag pkg-config
    description: Use pkgconfig to resolve C dependencies
    manual: True
    default: True

flag build-tool-depends
    description: Use build-tool-depends for hs-bindgen-cli
    manual: True
    default: True

custom-setup
    setup-depends:
          hs-bindgen-hooks
        , haskell-wayland-core
        , base             >=4.21 && <5
        , Cabal            >=3.14 && <3.18
        , Cabal-hooks      >=3.14 && <3.18
        , microlens-ghc

common language
    default-language: GHC2024
    default-extensions:
          DuplicateRecordFields
          OverloadedStrings
          OverloadedLabels
          OverloadedRecordDot
          TemplateHaskell
          TypeFamilies
          PatternSynonyms
          LambdaCase
          DerivingVia
          DeriveAnyClass

library
    import: language
    exposed-modules:
          River
          River.Client
          River.InputManagement
          River.WindowManagement
          River.XkbBindings
          River.XkbConfig
          WL.Client
          WL.Viewporter
          -- Most exposed modules are determined at configure time
    other-modules:
          Paths_hswm_bindings
    autogen-modules:
          Paths_hswm_bindings
    build-depends:
          base                 >=4.21   && <4.23
        , containers           >=0.7    && <1.0
        , data-default         >=0.8    && <0.9
        --, deepseq              >=1.5.1  && <1.6
        --, hashable             >=1.5.1  && <1.6
        , template-haskell     >=2.23   && <2.25
        , unix                ^>=2.8.6
        , unliftio            ^>=0.2.25
        --, c-expr-runtime       >=0.1.0  && <0.2
        , hs-bindgen-runtime   >=0.1.0  && <0.2
        , hs-bindgen-hooks     ==0.1.0.0
        --, pretty
        , haskell-wayland-core
    hs-source-dirs: src
    ghc-options: -Wall -Wunused-packages -fPIC

    if flag(pkg-config)
        pkgconfig-depends:
              wayland-client     >= 1.24
            , wayland-server     >= 1.24
            , wayland-protocols  >= 1.48
    else
        extra-libraries:
              wayland-client
            , wayland-server

    if flag(build-tool-depends)
       build-tool-depends: hs-bindgen:hs-bindgen-cli

test-suite spec
    import: language
    type: exitcode-stdio-1.0
    other-modules:
          Paths_hswm_bindings
          Wayland.UtilSpec
    autogen-modules:
          Paths_hswm_bindings
    build-depends:
          base
        , data-default
        , hspec
        , hs-bindgen-runtime   >=0.1.0  && <0.2
        , hswm-bindings
    build-tool-depends:
        hspec-discover:hspec-discover
    main-is: Spec.hs
    hs-source-dirs: tests
    ghc-options: -threaded -with-rtsopts=-N
