verbatim:
  cabal-version:      3.4
name:               hswm-bindings
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@5gsystems.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md
extra-source-files:
  - ../cbits/*.c
  - ../cbits/*.h

library:
  source-dirs: src
  dependencies:
    - base >=4.21.0.0
    - c-expr-runtime
    - hs-bindgen-runtime
    - template-haskell
  include-dirs:
    - ../cbits
    - ../cbits/wayland-protocols
  c-sources:
    - ../cbits/*.c
    - ../cbits/wayland-protocols/ext-foreign-toplevel-list-v1-protocol.c
  pkgconfig-depends:
    - wayland-client
    - pixman-1
  extra-libraries:
    - wayland-client
    - pixman-1
  ghc-options:
    - -Wall
    - -Wunused-packages
    - -fPIC
  language: GHC2024
