verbatim:
  cabal-version:      3.12
name:               hswm-bindings
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Samuli Thomasson
maintainer:         samuli.thomasson@pm.me
build-type:         Custom
extra-doc-files:    CHANGELOG.md
tested-with:
  - GHC == 9.12.2
  - GHC == 9.14.1

custom-setup:
  dependencies:
    - &base
      base  >=4.21 && <4.23
    - Cabal >=3.14 && <3.17

extra-source-files:
  - Makefile
  - binding-specs/*.yaml
  - generated/*.yaml
  - protocol/**/*.xml
  - cbits/**/*.c
  - include/**/*.h

flags:
  use-pkgconfig:
    description: Use pkgconfig to to resolve C dependencies
    default: true
    manual: true

library:
  source-dirs: src
  dependencies:
    - *base
    - template-haskell    >=2.23   && <2.25
    - data-default       ^>=0.8.0
    - hashable           ^>=1.5.1
    - text               ^>=2.1.2
    - deepseq            ^>=1.5.1
    - xml-conduit        ^>=1.10.1
    - hs-bindgen-runtime ^>=0.1.0
    - c-expr-runtime     ^>=0.1.0
    - unix
    - containers
    - unliftio
  language: GHC2024
  default-extensions:
    - DuplicateRecordFields
    - OverloadedStrings
    - OverloadedLabels
    - TemplateHaskell
    - TypeFamilies
    - PatternSynonyms
  ghc-options:
    - -Wall
    - -Wunused-packages
    - -fPIC
  include-dirs:
    - include
    - include/wayland-protocols
  when:
    - condition: flag(use-pkgconfig)
      then:
        pkgconfig-depends:
          - pixman-1
          - wayland-client
          - wayland-protocols
      else:
        extra-libraries:
          - pixman-1
          - wayland-client

tests:
  test-suite:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - base
      - hswm-bindings
      - hspec
    build-tools:
      - hspec-discover:hspec-discover
